#!/usr/bin/env python3
"""
Insert vocabulary_translations for Asian + remaining locales:
ja, ko, vi, th, zh-Hans, zh-Hant, id, hi, ar, pl, ro, uk
"""
import json, sys
from urllib.request import Request, urlopen
from urllib.error import HTTPError

URL = 'https://gmpjkoajhhwvxwsdohll.supabase.co'
KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtcGprb2FqaGh3dnh3c2RvaGxsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4Mjk4Mzk0NSwiZXhwIjoyMDk4NTU5OTQ1fQ.iHoqQdpjq3_vCMuuHEs9Y9in_lpKQ_cCRaI3EtJ6tKc'

def supa_get(table, params=''):
    req = Request(f'{URL}/rest/v1/{table}?{params}', headers={'apikey': KEY, 'Authorization': f'Bearer {KEY}'})
    return json.loads(urlopen(req).read())

def supa_post(table, rows):
    req = Request(f'{URL}/rest/v1/{table}',
        data=json.dumps(rows).encode('utf-8'),
        headers={
            'apikey': KEY, 'Authorization': f'Bearer {KEY}',
            'Content-Type': 'application/json',
            'Prefer': 'resolution=ignore-duplicates',
        }, method='POST')
    try:
        resp = urlopen(req)
        return resp.status, len(rows)
    except HTTPError as e:
        body = e.read().decode()[:300]
        print(f"    POST error {e.code}: {body}")
        return e.code, 0

vocab_en = supa_get('vocabulary_translations', 'select=vocabulary_id,meaning,example_sentence&locale=eq.en&order=vocabulary_id&limit=500')
print(f"Loaded {len(vocab_en)} EN vocabulary items")

# ─── JAPANESE ───────────────────────────────────────────────────────────
JA = {
    '"and...?" particle': '「…は？」の助詞', 'China': '中国', 'Chinese (written)': '中国語（書き言葉）',
    'Chinese character': '漢字', 'Chinese language': '中国語', 'I, me': '私',
    'Sunday': '日曜日', 'a few, some': 'いくつか', 'a little': '少し',
    'a moment, a quick action': 'ちょっと、素早い動作', 'after, behind': '後ろ、後',
    'afternoon': '午後', 'again': 'また', 'airplane': '飛行機', 'all': '全部',
    'also': 'も', 'and, with': 'と', 'apple': 'りんご', 'before, in front': '前',
    'big': '大きい', 'book': '本', 'bookstore': '本屋', 'boyfriend': '彼氏',
    'bread': 'パン', 'breakfast': '朝食', 'busy': '忙しい', 'can (permission)': '～できる（許可）',
    'can, to be able to': '～できる', 'can, to know how to': '～できる（技能）',
    'car, vehicle': '車', 'cat': '猫', 'chair': '椅子', 'character (writing)': '文字',
    'cheap': '安い', 'child': '子供', 'child (affectionate)': '子供（愛称）',
    'cinema': '映画館', 'class, lesson': '授業', 'classifier for animals; only': '～匹；だけ',
    'classifier for books': '～冊', 'classifier for clothes/matters': '～件',
    'classmate': 'クラスメート', 'clothing': '服', 'cold': '寒い', 'company': '会社',
    'completed-action particle': '完了の助詞', 'computer': 'パソコン', 'cooked rice': 'ご飯',
    'correct; towards': '正しい；～に向かって', 'country': '国', 'cup, glass': 'コップ',
    'dad': 'お父さん', 'daughter': '娘', 'day, sky': '日、空', 'day, sun': '日、太陽',
    'daytime': '昼間', 'dinner': '夕食', 'dish, vegetable': '料理、野菜', 'doctor': '医者',
    'dog': '犬', 'dumplings': '餃子', 'early': '早い', 'early morning': '早朝',
    'egg': '卵', 'eight': '八', 'evening': '夜', 'everyone': 'みんな',
    'excuse me (to ask)': 'すみません（質問）', 'expensive': '高い', 'extremely': '非常に',
    'family members': '家族', 'female': '女性', 'few, less': '少ない', 'film': '映画',
    'first name': '名前', 'five': '五', 'four': '四', 'friend': '友達', 'fruit': '果物',
    'fun': '楽しい', 'general classifier': '～個（一般量詞）', 'girlfriend': '彼女',
    'good, well': '良い', 'goodbye': 'さようなら', 'half': '半分',
    'happy, glad': '嬉しい', 'he': '彼', 'hello': 'こんにちは',
    'hello (phone)': 'もしもし', 'here': 'ここ', 'home, family': '家、家族',
    'hospital': '病院', 'hot': '暑い', 'hour (duration)': '～時間',
    'how': 'どう', 'how (about), what do you think': 'どう思う',
    'how many (small number)': 'いくつ', 'how much': 'いくら', 'hundred': '百',
    'illness, to be sick': '病気', 'inside': '中', 'it (object/animal)': 'それ',
    "it's alright, no problem": '大丈夫', "it's fine, no big deal": '問題ない',
    'last year': '去年', 'late': '遅い', 'lunch': '昼食', 'madam, Ms.': '～さん（女性）',
    'male': '男性', 'many, much': '多い', 'matter, thing': 'こと',
    'meal, cooked rice': '食事、ご飯', 'middle/high school': '中学・高校',
    'middle/high school student': '中高生', 'milk': '牛乳', 'minute (duration)': '～分',
    "minute; point (score)": '分；点', 'mister': '～さん（男性）', 'mobile phone': '携帯電話',
    'mom': 'お母さん', 'moment': '瞬間', 'money': 'お金', 'month, moon': '月',
    'morning (before noon)': '午前', 'mouth; classifier for family members': '口；～人',
    'new': '新しい', 'next year': '来年', 'nice to look at': 'きれい',
    'nine': '九', 'noodles': '麺', 'noon': '正午', 'not': '～ない',
    'not (to have/past)': '～なかった', 'now': '今', 'number; day of the month': '番号；日',
    "o'clock; a bit; point": '～時；少し；点', 'older brother': '兄',
    'older sister': '姉', 'on, above; to go up': '上；上がる', 'one': '一',
    'ordinal prefix': '第～', 'outside': '外', 'over there': 'あそこ',
    'person, people': '人', 'pleasant to hear': '聞き心地が良い',
    'please; to invite': 'どうぞ；招待する', 'plural suffix': '～たち',
    'possessive particle': '～の', 'pretty, beautiful': 'きれい、美しい',
    'primary school': '小学校', 'primary school student': '小学生',
    'problem, question': '問題', 'rain': '雨', 'really': '本当に',
    'restaurant, hotel': 'レストラン、ホテル', 'room': '部屋', 'school': '学校',
    'seven': '七', 'she': '彼女', 'shop': '店', 'shop, store': '店、お店',
    'side, edge': '横、端', 'six': '六', 'small': '小さい', 'snow': '雪',
    'some (people)': '一部の人', 'some, a bit': '少し', 'some, a few': 'いくつか',
    'son': '息子', 'song': '歌', 'sorry': 'ごめんなさい', 'steamed bun': '肉まん',
    'still, also': 'まだ、も', 'structural particle': '構造助詞',
    'student': '学生', 'suggestion particle': '提案の助詞', 'supermarket': 'スーパー',
    'table': 'テーブル', 'tasty': 'おいしい', 'taxi': 'タクシー', 'tea': 'お茶',
    'teacher': '先生', 'telephone': '電話', 'television': 'テレビ', 'ten': '十',
    'thank you': 'ありがとう', 'that (over there)': 'あれ', 'that one': 'あの',
    'there': 'そこ', 'these': 'これら', 'they': '彼ら', 'they (female)': '彼女ら',
    'they (objects/animals)': 'それら', 'thing, object': '物', 'this': 'この',
    'this one': 'これ', 'this way': 'こちら', 'this year': '今年',
    'those': 'あれら', 'thousand': '千', 'three': '三', 'time': '時間',
    'to arrive': '着く', 'to ask': '聞く', 'to be': '～です', 'to be -ing': '～している',
    'to be at; -ing': '～にいる；～している', 'to be called': '～という名前',
    'to buy': '買う', 'to come': '来る', 'to cook': '料理する', 'to do': 'する',
    'to drink': '飲む', 'to drive': '運転する', 'to eat': '食べる',
    'to fall ill': '病気になる', 'to finish class': '授業が終わる',
    'to finish work': '仕事が終わる', 'to get up': '起きる', 'to give; for': 'あげる；～のために',
    'to go': '行く', 'to go to class': '授業に行く', 'to go to school': '学校に行く',
    'to go to work': '仕事に行く', 'to have': '持っている', 'to have, there is': 'ある、いる',
    'to hear': '聞こえる', 'to know (a fact)': '知る', 'to know (a person)': '知っている（人）',
    'to like': '好き', 'to listen': '聞く', 'to live (reside)': '住む',
    'to look for': '探す', 'to look, to read': '見る、読む', 'to love': '愛する',
    'to make a phone call': '電話をかける', 'to not want': '要らない',
    'to open': '開ける', 'to play, to have fun': '遊ぶ', 'to rain': '雨が降る',
    'to read': '読む', 'to rest': '休む', 'to return': '帰る',
    'to see a doctor': '医者に行く', 'to see, to catch sight of': '見える',
    'to see, to meet': '会う', 'to sell': '売る', 'to sing': '歌う',
    'to sit; to take (transport)': '座る；乗る', 'to sleep': '寝る',
    'to sleep (go to bed)': '寝る（就寝）', 'to speak, to say': '話す、言う',
    'to study': '勉強する', 'to study, to learn': '勉強する、学ぶ',
    'to study, to read': '勉強する、読む', 'to talk, to chat': '話す、おしゃべり',
    'to think, to feel': '思う、感じる', 'to want, to think': '欲しい、思う',
    'to want; to need': '欲しい；必要', 'to wear': '着る', 'to work; job': '働く；仕事',
    'to write': '書く', 'today': '今日', 'tomorrow': '明日', 'too (excessive)': '～すぎる',
    'train': '電車', 'two': '二', 'two (before classifier)': '二（量詞前）',
    'under; to go down': '下；降りる', 'university': '大学', 'university student': '大学生',
    'very, rather': 'とても', 'water': '水', 'we': '私たち', 'weather': '天気',
    'week': '週', 'what': '何', 'where': 'どこ', 'which': 'どの',
    'which one': 'どれ', 'which ones': 'どれら', 'who': '誰', 'year': '年',
    'years old': '歳', 'yes/no question particle': '疑問助詞', 'yesterday': '昨日',
    'you': 'あなた', 'you (plural)': 'あなたたち', 'you (polite)': 'あなた（丁寧）',
    "you're welcome": 'どういたしまして', 'younger brother': '弟', 'younger sister': '妹',
    'yuan (currency)': '元（通貨）', 'yuan (currency); piece': '元（通貨）；個', 'zero': '零',
}

# ─── KOREAN ─────────────────────────────────────────────────────────────
KO = {
    '"and...?" particle': '"그리고...?" 조사', 'China': '중국', 'Chinese (written)': '중국어 (문어)',
    'Chinese character': '한자', 'Chinese language': '중국어', 'I, me': '나, 저',
    'Sunday': '일요일', 'a few, some': '몇 개', 'a little': '조금',
    'a moment, a quick action': '잠깐, 빠른 동작', 'after, behind': '후, 뒤',
    'afternoon': '오후', 'again': '또', 'airplane': '비행기', 'all': '모두',
    'also': '도', 'and, with': '그리고, ~와', 'apple': '사과', 'before, in front': '전, 앞',
    'big': '큰', 'book': '책', 'bookstore': '서점', 'boyfriend': '남자친구',
    'bread': '빵', 'breakfast': '아침식사', 'busy': '바쁜', 'can (permission)': '~해도 되다',
    'can, to be able to': '~할 수 있다', 'can, to know how to': '~할 줄 알다',
    'car, vehicle': '차, 자동차', 'cat': '고양이', 'chair': '의자',
    'character (writing)': '글자', 'cheap': '싼', 'child': '아이',
    'child (affectionate)': '아이 (애칭)', 'cinema': '영화관', 'class, lesson': '수업',
    'classifier for animals; only': '~마리; 만', 'classifier for books': '~권',
    'classifier for clothes/matters': '~벌/~건', 'classmate': '반 친구',
    'clothing': '옷', 'cold': '추운', 'company': '회사',
    'completed-action particle': '완료 조사', 'computer': '컴퓨터',
    'cooked rice': '밥', 'correct; towards': '맞다; ~를 향해', 'country': '나라',
    'cup, glass': '컵, 잔', 'dad': '아빠', 'daughter': '딸',
    'day, sky': '날, 하늘', 'day, sun': '날, 해', 'daytime': '낮',
    'dinner': '저녁식사', 'dish, vegetable': '요리, 채소', 'doctor': '의사',
    'dog': '개', 'dumplings': '만두', 'early': '이른', 'early morning': '이른 아침',
    'egg': '계란', 'eight': '팔', 'evening': '저녁', 'everyone': '모두',
    'excuse me (to ask)': '실례합니다 (질문)', 'expensive': '비싼',
    'extremely': '매우', 'family members': '가족', 'female': '여성',
    'few, less': '적은', 'film': '영화', 'first name': '이름',
    'five': '오', 'four': '사', 'friend': '친구', 'fruit': '과일',
    'fun': '재미있는', 'general classifier': '~개 (일반 분류사)',
    'girlfriend': '여자친구', 'good, well': '좋은, 잘', 'goodbye': '안녕히 가세요',
    'half': '반', 'happy, glad': '행복한, 기쁜', 'he': '그',
    'hello': '안녕하세요', 'hello (phone)': '여보세요', 'here': '여기',
    'home, family': '집, 가족', 'hospital': '병원', 'hot': '더운',
    'hour (duration)': '~시간', 'how': '어떻게',
    'how (about), what do you think': '어때요', 'how many (small number)': '몇',
    'how much': '얼마', 'hundred': '백', 'illness, to be sick': '병, 아프다',
    'inside': '안', 'it (object/animal)': '그것',
    "it's alright, no problem": '괜찮아요', "it's fine, no big deal": '별거 아니에요',
    'last year': '작년', 'late': '늦은', 'lunch': '점심', 'madam, Ms.': '~씨 (여성)',
    'male': '남성', 'many, much': '많은', 'matter, thing': '일, 것',
    'meal, cooked rice': '식사, 밥', 'middle/high school': '중·고등학교',
    'middle/high school student': '중·고등학생', 'milk': '우유',
    'minute (duration)': '~분', "minute; point (score)": '분; 점',
    'mister': '~씨 (남성)', 'mobile phone': '핸드폰', 'mom': '엄마',
    'moment': '순간', 'money': '돈', 'month, moon': '월, 달',
    'morning (before noon)': '오전', 'mouth; classifier for family members': '입; ~명',
    'new': '새로운', 'next year': '내년', 'nice to look at': '보기 좋은',
    'nine': '구', 'noodles': '국수', 'noon': '정오', 'not': '~않다',
    'not (to have/past)': '~없다/~않았다', 'now': '지금',
    'number; day of the month': '번호; ~일', "o'clock; a bit; point": '~시; 조금; 점',
    'older brother': '형/오빠', 'older sister': '누나/언니',
    'on, above; to go up': '위; 올라가다', 'one': '일',
    'ordinal prefix': '제~', 'outside': '밖', 'over there': '저기',
    'person, people': '사람', 'pleasant to hear': '듣기 좋은',
    'please; to invite': '~해주세요; 초대하다', 'plural suffix': '~들',
    'possessive particle': '~의', 'pretty, beautiful': '예쁜, 아름다운',
    'primary school': '초등학교', 'primary school student': '초등학생',
    'problem, question': '문제', 'rain': '비', 'really': '정말',
    'restaurant, hotel': '식당, 호텔', 'room': '방', 'school': '학교',
    'seven': '칠', 'she': '그녀', 'shop': '가게', 'shop, store': '가게, 상점',
    'side, edge': '옆, 가장자리', 'six': '육', 'small': '작은', 'snow': '눈',
    'some (people)': '일부 사람', 'some, a bit': '약간', 'some, a few': '몇 개',
    'son': '아들', 'song': '노래', 'sorry': '미안합니다',
    'steamed bun': '찐빵', 'still, also': '아직, 도', 'structural particle': '구조 조사',
    'student': '학생', 'suggestion particle': '제안 조사', 'supermarket': '슈퍼마켓',
    'table': '탁자', 'tasty': '맛있는', 'taxi': '택시', 'tea': '차',
    'teacher': '선생님', 'telephone': '전화', 'television': '텔레비전', 'ten': '십',
    'thank you': '감사합니다', 'that (over there)': '저것', 'that one': '그',
    'there': '거기', 'these': '이것들', 'they': '그들',
    'they (female)': '그녀들', 'they (objects/animals)': '그것들',
    'thing, object': '물건', 'this': '이', 'this one': '이것',
    'this way': '이쪽', 'this year': '올해', 'those': '저것들',
    'thousand': '천', 'three': '삼', 'time': '시간', 'to arrive': '도착하다',
    'to ask': '묻다', 'to be': '~이다', 'to be -ing': '~하고 있다',
    'to be at; -ing': '~에 있다; ~하는 중', 'to be called': '~라고 하다',
    'to buy': '사다', 'to come': '오다', 'to cook': '요리하다', 'to do': '하다',
    'to drink': '마시다', 'to drive': '운전하다', 'to eat': '먹다',
    'to fall ill': '아프다', 'to finish class': '수업이 끝나다',
    'to finish work': '퇴근하다', 'to get up': '일어나다',
    'to give; for': '주다; ~를 위해', 'to go': '가다',
    'to go to class': '수업에 가다', 'to go to school': '학교에 가다',
    'to go to work': '출근하다', 'to have': '가지다', 'to have, there is': '있다',
    'to hear': '듣다', 'to know (a fact)': '알다', 'to know (a person)': '알다 (사람)',
    'to like': '좋아하다', 'to listen': '듣다', 'to live (reside)': '살다',
    'to look for': '찾다', 'to look, to read': '보다, 읽다', 'to love': '사랑하다',
    'to make a phone call': '전화하다', 'to not want': '원하지 않다',
    'to open': '열다', 'to play, to have fun': '놀다', 'to rain': '비가 오다',
    'to read': '읽다', 'to rest': '쉬다', 'to return': '돌아가다',
    'to see a doctor': '진찰받다', 'to see, to catch sight of': '보이다',
    'to see, to meet': '만나다', 'to sell': '팔다', 'to sing': '노래하다',
    'to sit; to take (transport)': '앉다; 타다', 'to sleep': '자다',
    'to sleep (go to bed)': '자다 (잠자리)', 'to speak, to say': '말하다',
    'to study': '공부하다', 'to study, to learn': '공부하다, 배우다',
    'to study, to read': '공부하다, 읽다', 'to talk, to chat': '이야기하다',
    'to think, to feel': '생각하다, 느끼다', 'to want, to think': '원하다, 생각하다',
    'to want; to need': '원하다; 필요하다', 'to wear': '입다',
    'to work; job': '일하다; 직업', 'to write': '쓰다', 'today': '오늘',
    'tomorrow': '내일', 'too (excessive)': '너무', 'train': '기차',
    'two': '이', 'two (before classifier)': '두 (분류사 전)', 'under; to go down': '아래; 내려가다',
    'university': '대학교', 'university student': '대학생', 'very, rather': '매우, 꽤',
    'water': '물', 'we': '우리', 'weather': '날씨', 'week': '주',
    'what': '무엇', 'where': '어디', 'which': '어느', 'which one': '어느 것',
    'which ones': '어느 것들', 'who': '누구', 'year': '년', 'years old': '살',
    'yes/no question particle': '예/아니오 의문 조사', 'yesterday': '어제',
    'you': '너, 당신', 'you (plural)': '너희, 여러분', 'you (polite)': '당신 (존칭)',
    "you're welcome": '천만에요', 'younger brother': '남동생', 'younger sister': '여동생',
    'yuan (currency)': '위안 (화폐)', 'yuan (currency); piece': '위안; 개', 'zero': '영',
}

# ─── VIETNAMESE ──────────────────────────────────────────────────────────
VI = {
    '"and...?" particle': 'trợ từ "còn...?"', 'China': 'Trung Quốc',
    'Chinese (written)': 'tiếng Trung (viết)', 'Chinese character': 'chữ Hán',
    'Chinese language': 'tiếng Trung', 'I, me': 'tôi', 'Sunday': 'Chủ nhật',
    'a few, some': 'một vài', 'a little': 'một chút',
    'a moment, a quick action': 'một lát, hành động nhanh',
    'after, behind': 'sau, phía sau', 'afternoon': 'buổi chiều', 'again': 'lại',
    'airplane': 'máy bay', 'all': 'tất cả', 'also': 'cũng',
    'and, with': 'và, với', 'apple': 'quả táo', 'before, in front': 'trước',
    'big': 'to, lớn', 'book': 'sách', 'bookstore': 'nhà sách',
    'boyfriend': 'bạn trai', 'bread': 'bánh mì', 'breakfast': 'bữa sáng',
    'busy': 'bận', 'can (permission)': 'có thể (được phép)',
    'can, to be able to': 'có thể', 'can, to know how to': 'biết (làm)',
    'car, vehicle': 'xe, ô tô', 'cat': 'con mèo', 'chair': 'ghế',
    'character (writing)': 'chữ (viết)', 'cheap': 'rẻ', 'child': 'trẻ em',
    'child (affectionate)': 'con (thân mật)', 'cinema': 'rạp phim',
    'class, lesson': 'lớp học, bài học', 'classifier for animals; only': 'con; chỉ',
    'classifier for books': 'cuốn', 'classifier for clothes/matters': 'bộ/việc',
    'classmate': 'bạn cùng lớp', 'clothing': 'quần áo', 'cold': 'lạnh',
    'company': 'công ty', 'completed-action particle': 'trợ từ hoàn thành',
    'computer': 'máy tính', 'cooked rice': 'cơm',
    'correct; towards': 'đúng; hướng về', 'country': 'nước',
    'cup, glass': 'cốc, ly', 'dad': 'bố', 'daughter': 'con gái',
    'day, sky': 'ngày, trời', 'day, sun': 'ngày, mặt trời', 'daytime': 'ban ngày',
    'dinner': 'bữa tối', 'dish, vegetable': 'món ăn, rau', 'doctor': 'bác sĩ',
    'dog': 'con chó', 'dumplings': 'sủi cảo', 'early': 'sớm',
    'early morning': 'sáng sớm', 'egg': 'trứng', 'eight': 'tám',
    'evening': 'buổi tối', 'everyone': 'mọi người',
    'excuse me (to ask)': 'xin lỗi (hỏi)', 'expensive': 'đắt',
    'extremely': 'cực kỳ', 'family members': 'thành viên gia đình',
    'female': 'nữ', 'few, less': 'ít', 'film': 'phim', 'first name': 'tên',
    'five': 'năm', 'four': 'bốn', 'friend': 'bạn', 'fruit': 'trái cây',
    'fun': 'vui', 'general classifier': 'cái (lượng từ chung)',
    'girlfriend': 'bạn gái', 'good, well': 'tốt', 'goodbye': 'tạm biệt',
    'half': 'nửa', 'happy, glad': 'vui, hạnh phúc', 'he': 'anh ấy',
    'hello': 'xin chào', 'hello (phone)': 'a lô', 'here': 'đây',
    'home, family': 'nhà, gia đình', 'hospital': 'bệnh viện', 'hot': 'nóng',
    'hour (duration)': 'giờ (thời lượng)', 'how': 'thế nào',
    'how (about), what do you think': 'thế nào, bạn nghĩ sao',
    'how many (small number)': 'mấy', 'how much': 'bao nhiêu', 'hundred': 'trăm',
    'illness, to be sick': 'bệnh, ốm', 'inside': 'bên trong',
    'it (object/animal)': 'nó', "it's alright, no problem": 'không sao',
    "it's fine, no big deal": 'không vấn đề gì', 'last year': 'năm ngoái',
    'late': 'muộn', 'lunch': 'bữa trưa', 'madam, Ms.': 'bà, cô',
    'male': 'nam', 'many, much': 'nhiều', 'matter, thing': 'việc, chuyện',
    'meal, cooked rice': 'bữa ăn, cơm', 'middle/high school': 'trường trung học',
    'middle/high school student': 'học sinh trung học', 'milk': 'sữa',
    'minute (duration)': 'phút', "minute; point (score)": 'phút; điểm',
    'mister': 'ông', 'mobile phone': 'điện thoại di động', 'mom': 'mẹ',
    'moment': 'khoảnh khắc', 'money': 'tiền', 'month, moon': 'tháng, trăng',
    'morning (before noon)': 'buổi sáng', 'mouth; classifier for family members': 'miệng; người',
    'new': 'mới', 'next year': 'năm sau', 'nice to look at': 'đẹp',
    'nine': 'chín', 'noodles': 'mì', 'noon': 'trưa', 'not': 'không',
    'not (to have/past)': 'không (có/đã)', 'now': 'bây giờ',
    'number; day of the month': 'số; ngày trong tháng',
    "o'clock; a bit; point": 'giờ; một chút; điểm',
    'older brother': 'anh trai', 'older sister': 'chị gái',
    'on, above; to go up': 'trên; đi lên', 'one': 'một',
    'ordinal prefix': 'thứ', 'outside': 'bên ngoài', 'over there': 'đằng kia',
    'person, people': 'người', 'pleasant to hear': 'nghe hay',
    'please; to invite': 'xin mời', 'plural suffix': 'hậu tố số nhiều',
    'possessive particle': 'trợ từ sở hữu', 'pretty, beautiful': 'đẹp',
    'primary school': 'trường tiểu học', 'primary school student': 'học sinh tiểu học',
    'problem, question': 'vấn đề, câu hỏi', 'rain': 'mưa', 'really': 'thật sự',
    'restaurant, hotel': 'nhà hàng, khách sạn', 'room': 'phòng', 'school': 'trường',
    'seven': 'bảy', 'she': 'cô ấy', 'shop': 'cửa hàng', 'shop, store': 'cửa hàng',
    'side, edge': 'bên, mép', 'six': 'sáu', 'small': 'nhỏ', 'snow': 'tuyết',
    'some (people)': 'một số người', 'some, a bit': 'một chút',
    'some, a few': 'một vài', 'son': 'con trai', 'song': 'bài hát',
    'sorry': 'xin lỗi', 'steamed bun': 'bánh bao',
    'still, also': 'vẫn, cũng', 'structural particle': 'trợ từ cấu trúc',
    'student': 'học sinh', 'suggestion particle': 'trợ từ đề nghị',
    'supermarket': 'siêu thị', 'table': 'bàn', 'tasty': 'ngon',
    'taxi': 'taxi', 'tea': 'trà', 'teacher': 'giáo viên', 'telephone': 'điện thoại',
    'television': 'tivi', 'ten': 'mười', 'thank you': 'cảm ơn',
    'that (over there)': 'kia', 'that one': 'cái đó', 'there': 'đó',
    'these': 'những cái này', 'they': 'họ', 'they (female)': 'họ (nữ)',
    'they (objects/animals)': 'chúng nó', 'thing, object': 'đồ vật',
    'this': 'này', 'this one': 'cái này', 'this way': 'bên này',
    'this year': 'năm nay', 'those': 'những cái kia', 'thousand': 'nghìn',
    'three': 'ba', 'time': 'thời gian', 'to arrive': 'đến',
    'to ask': 'hỏi', 'to be': 'là', 'to be -ing': 'đang',
    'to be at; -ing': 'ở; đang', 'to be called': 'tên là',
    'to buy': 'mua', 'to come': 'đến', 'to cook': 'nấu ăn',
    'to do': 'làm', 'to drink': 'uống', 'to drive': 'lái xe',
    'to eat': 'ăn', 'to fall ill': 'bị ốm', 'to finish class': 'tan học',
    'to finish work': 'tan làm', 'to get up': 'dậy',
    'to give; for': 'cho; cho', 'to go': 'đi', 'to go to class': 'đi học',
    'to go to school': 'đi học', 'to go to work': 'đi làm',
    'to have': 'có', 'to have, there is': 'có', 'to hear': 'nghe thấy',
    'to know (a fact)': 'biết', 'to know (a person)': 'biết (người)',
    'to like': 'thích', 'to listen': 'nghe', 'to live (reside)': 'sống, ở',
    'to look for': 'tìm', 'to look, to read': 'xem, đọc', 'to love': 'yêu',
    'to make a phone call': 'gọi điện', 'to not want': 'không muốn',
    'to open': 'mở', 'to play, to have fun': 'chơi', 'to rain': 'mưa',
    'to read': 'đọc', 'to rest': 'nghỉ ngơi', 'to return': 'trở về',
    'to see a doctor': 'đi khám bệnh', 'to see, to catch sight of': 'nhìn thấy',
    'to see, to meet': 'gặp', 'to sell': 'bán', 'to sing': 'hát',
    'to sit; to take (transport)': 'ngồi; đi (phương tiện)',
    'to sleep': 'ngủ', 'to sleep (go to bed)': 'đi ngủ',
    'to speak, to say': 'nói', 'to study': 'học',
    'to study, to learn': 'học, học tập', 'to study, to read': 'học, đọc',
    'to talk, to chat': 'nói chuyện', 'to think, to feel': 'nghĩ, cảm thấy',
    'to want, to think': 'muốn, nghĩ', 'to want; to need': 'muốn; cần',
    'to wear': 'mặc', 'to work; job': 'làm việc; công việc', 'to write': 'viết',
    'today': 'hôm nay', 'tomorrow': 'ngày mai', 'too (excessive)': 'quá',
    'train': 'tàu hỏa', 'two': 'hai', 'two (before classifier)': 'hai (trước lượng từ)',
    'under; to go down': 'dưới; đi xuống', 'university': 'đại học',
    'university student': 'sinh viên', 'very, rather': 'rất, khá',
    'water': 'nước', 'we': 'chúng tôi', 'weather': 'thời tiết',
    'week': 'tuần', 'what': 'cái gì', 'where': 'ở đâu', 'which': 'nào',
    'which one': 'cái nào', 'which ones': 'những cái nào', 'who': 'ai',
    'year': 'năm', 'years old': 'tuổi', 'yes/no question particle': 'trợ từ nghi vấn',
    'yesterday': 'hôm qua', 'you': 'bạn', 'you (plural)': 'các bạn',
    'you (polite)': 'anh/chị', "you're welcome": 'không có gì',
    'younger brother': 'em trai', 'younger sister': 'em gái',
    'yuan (currency)': 'nhân dân tệ', 'yuan (currency); piece': 'nhân dân tệ; cái',
    'zero': 'không',
}

# ─── THAI ────────────────────────────────────────────────────────────────
TH = {
    '"and...?" particle': 'อนุภาค "แล้ว...?"', 'China': 'จีน',
    'Chinese (written)': 'ภาษาจีน (เขียน)', 'Chinese character': 'ตัวอักษรจีน',
    'Chinese language': 'ภาษาจีน', 'I, me': 'ฉัน', 'Sunday': 'วันอาทิตย์',
    'a few, some': 'สองสาม', 'a little': 'นิดหน่อย',
    'after, behind': 'หลัง, ข้างหลัง', 'afternoon': 'ตอนบ่าย', 'again': 'อีกครั้ง',
    'airplane': 'เครื่องบิน', 'all': 'ทั้งหมด', 'also': 'ด้วย',
    'and, with': 'และ, กับ', 'apple': 'แอปเปิ้ล', 'before, in front': 'ก่อน, ข้างหน้า',
    'big': 'ใหญ่', 'book': 'หนังสือ', 'bookstore': 'ร้านหนังสือ',
    'boyfriend': 'แฟน (ผู้ชาย)', 'bread': 'ขนมปัง', 'breakfast': 'อาหารเช้า',
    'busy': 'ยุ่ง', 'can, to be able to': 'สามารถ', 'car, vehicle': 'รถ',
    'cat': 'แมว', 'chair': 'เก้าอี้', 'cheap': 'ถูก', 'child': 'เด็ก',
    'cinema': 'โรงหนัง', 'class, lesson': 'ชั้นเรียน', 'classmate': 'เพื่อนร่วมชั้น',
    'clothing': 'เสื้อผ้า', 'cold': 'เย็น, หนาว', 'company': 'บริษัท',
    'computer': 'คอมพิวเตอร์', 'cooked rice': 'ข้าวสวย', 'country': 'ประเทศ',
    'cup, glass': 'แก้ว, ถ้วย', 'dad': 'พ่อ', 'daughter': 'ลูกสาว',
    'dinner': 'อาหารเย็น', 'doctor': 'หมอ', 'dog': 'สุนัข',
    'dumplings': 'เกี๊ยว', 'early': 'เช้า', 'egg': 'ไข่', 'eight': 'แปด',
    'evening': 'ตอนเย็น', 'everyone': 'ทุกคน', 'expensive': 'แพง',
    'family members': 'สมาชิกในครอบครัว', 'female': 'ผู้หญิง',
    'film': 'ภาพยนตร์', 'five': 'ห้า', 'four': 'สี่', 'friend': 'เพื่อน',
    'fruit': 'ผลไม้', 'fun': 'สนุก', 'girlfriend': 'แฟน (ผู้หญิง)',
    'good, well': 'ดี', 'goodbye': 'ลาก่อน', 'half': 'ครึ่ง',
    'happy, glad': 'มีความสุข', 'he': 'เขา (ผู้ชาย)', 'hello': 'สวัสดี',
    'here': 'ที่นี่', 'home, family': 'บ้าน, ครอบครัว', 'hospital': 'โรงพยาบาล',
    'hot': 'ร้อน', 'how': 'อย่างไร', 'how much': 'เท่าไหร่', 'hundred': 'ร้อย',
    'inside': 'ข้างใน', 'last year': 'ปีที่แล้ว', 'lunch': 'อาหารกลางวัน',
    'male': 'ผู้ชาย', 'many, much': 'มาก', 'milk': 'นม',
    'mobile phone': 'โทรศัพท์มือถือ', 'mom': 'แม่', 'money': 'เงิน',
    'month, moon': 'เดือน, พระจันทร์', 'new': 'ใหม่', 'next year': 'ปีหน้า',
    'nine': 'เก้า', 'noodles': 'ก๋วยเตี๋ยว', 'noon': 'เที่ยง',
    'not': 'ไม่', 'now': 'ตอนนี้', 'one': 'หนึ่ง', 'outside': 'ข้างนอก',
    'person, people': 'คน', 'rain': 'ฝน', 'really': 'จริงๆ',
    'restaurant, hotel': 'ร้านอาหาร, โรงแรม', 'room': 'ห้อง', 'school': 'โรงเรียน',
    'seven': 'เจ็ด', 'she': 'เขา (ผู้หญิง)', 'shop': 'ร้าน',
    'six': 'หก', 'small': 'เล็ก', 'snow': 'หิมะ', 'son': 'ลูกชาย',
    'song': 'เพลง', 'sorry': 'ขอโทษ', 'student': 'นักเรียน',
    'supermarket': 'ซูเปอร์มาร์เก็ต', 'table': 'โต๊ะ', 'tasty': 'อร่อย',
    'taxi': 'แท็กซี่', 'tea': 'ชา', 'teacher': 'ครู', 'telephone': 'โทรศัพท์',
    'television': 'โทรทัศน์', 'ten': 'สิบ', 'thank you': 'ขอบคุณ',
    'there': 'ที่นั่น', 'they': 'พวกเขา', 'this': 'นี้',
    'this year': 'ปีนี้', 'thousand': 'พัน', 'three': 'สาม',
    'time': 'เวลา', 'to arrive': 'มาถึง', 'to ask': 'ถาม',
    'to be': 'เป็น', 'to buy': 'ซื้อ', 'to come': 'มา',
    'to cook': 'ทำอาหาร', 'to do': 'ทำ', 'to drink': 'ดื่ม',
    'to drive': 'ขับรถ', 'to eat': 'กิน', 'to go': 'ไป',
    'to have': 'มี', 'to have, there is': 'มี', 'to know (a fact)': 'รู้',
    'to like': 'ชอบ', 'to listen': 'ฟัง', 'to live (reside)': 'อาศัยอยู่',
    'to look for': 'หา', 'to look, to read': 'ดู, อ่าน', 'to love': 'รัก',
    'to open': 'เปิด', 'to read': 'อ่าน', 'to rest': 'พักผ่อน',
    'to return': 'กลับ', 'to sell': 'ขาย', 'to sing': 'ร้องเพลง',
    'to sleep': 'นอน', 'to speak, to say': 'พูด', 'to study': 'เรียน',
    'to study, to learn': 'เรียน, เรียนรู้', 'to want, to think': 'อยาก, คิด',
    'to want; to need': 'อยาก; ต้องการ', 'to wear': 'ใส่',
    'to work; job': 'ทำงาน; งาน', 'to write': 'เขียน', 'today': 'วันนี้',
    'tomorrow': 'พรุ่งนี้', 'too (excessive)': 'เกินไป', 'train': 'รถไฟ',
    'two': 'สอง', 'under; to go down': 'ข้างล่าง; ลงไป',
    'university': 'มหาวิทยาลัย', 'very, rather': 'มาก, ค่อนข้าง',
    'water': 'น้ำ', 'we': 'เรา', 'weather': 'อากาศ', 'week': 'สัปดาห์',
    'what': 'อะไร', 'where': 'ที่ไหน', 'which': 'ไหน', 'who': 'ใคร',
    'year': 'ปี', 'years old': 'ขวบ/ปี', 'yesterday': 'เมื่อวาน',
    'you': 'คุณ', 'you (plural)': 'พวกคุณ', "you're welcome": 'ไม่เป็นไร',
    'younger brother': 'น้องชาย', 'younger sister': 'น้องสาว', 'zero': 'ศูนย์',
}

# ─── INDONESIAN ──────────────────────────────────────────────────────────
ID = {
    '"and...?" particle': 'partikel "lalu...?"', 'China': 'Tiongkok',
    'Chinese (written)': 'bahasa Mandarin (tulis)', 'Chinese character': 'aksara Tionghoa',
    'Chinese language': 'bahasa Mandarin', 'I, me': 'saya', 'Sunday': 'Minggu',
    'a few, some': 'beberapa', 'a little': 'sedikit',
    'after, behind': 'setelah, di belakang', 'afternoon': 'sore', 'again': 'lagi',
    'airplane': 'pesawat', 'all': 'semua', 'also': 'juga', 'and, with': 'dan, dengan',
    'apple': 'apel', 'before, in front': 'sebelum, di depan', 'big': 'besar',
    'book': 'buku', 'bookstore': 'toko buku', 'boyfriend': 'pacar (laki-laki)',
    'bread': 'roti', 'breakfast': 'sarapan', 'busy': 'sibuk',
    'can, to be able to': 'bisa, dapat', 'car, vehicle': 'mobil, kendaraan',
    'cat': 'kucing', 'chair': 'kursi', 'cheap': 'murah', 'child': 'anak',
    'cinema': 'bioskop', 'class, lesson': 'kelas, pelajaran', 'classmate': 'teman sekelas',
    'clothing': 'pakaian', 'cold': 'dingin', 'company': 'perusahaan',
    'computer': 'komputer', 'cooked rice': 'nasi', 'country': 'negara',
    'cup, glass': 'cangkir, gelas', 'dad': 'ayah', 'daughter': 'putri',
    'dinner': 'makan malam', 'doctor': 'dokter', 'dog': 'anjing',
    'dumplings': 'pangsit', 'early': 'pagi', 'egg': 'telur', 'eight': 'delapan',
    'evening': 'malam', 'everyone': 'semua orang', 'expensive': 'mahal',
    'family members': 'anggota keluarga', 'female': 'perempuan', 'film': 'film',
    'five': 'lima', 'four': 'empat', 'friend': 'teman', 'fruit': 'buah',
    'fun': 'menyenangkan', 'girlfriend': 'pacar (perempuan)',
    'good, well': 'baik, bagus', 'goodbye': 'selamat tinggal', 'half': 'setengah',
    'happy, glad': 'senang, gembira', 'he': 'dia (laki-laki)', 'hello': 'halo',
    'here': 'di sini', 'home, family': 'rumah, keluarga', 'hospital': 'rumah sakit',
    'hot': 'panas', 'how': 'bagaimana', 'how much': 'berapa', 'hundred': 'seratus',
    'inside': 'di dalam', 'last year': 'tahun lalu', 'lunch': 'makan siang',
    'male': 'laki-laki', 'many, much': 'banyak', 'milk': 'susu',
    'mobile phone': 'telepon genggam', 'mom': 'ibu', 'money': 'uang',
    'month, moon': 'bulan', 'new': 'baru', 'next year': 'tahun depan',
    'nine': 'sembilan', 'noodles': 'mie', 'noon': 'siang', 'not': 'tidak',
    'now': 'sekarang', 'one': 'satu', 'outside': 'di luar',
    'person, people': 'orang', 'rain': 'hujan', 'really': 'benar-benar',
    'restaurant, hotel': 'restoran, hotel', 'room': 'kamar', 'school': 'sekolah',
    'seven': 'tujuh', 'she': 'dia (perempuan)', 'shop': 'toko',
    'six': 'enam', 'small': 'kecil', 'snow': 'salju', 'son': 'putra',
    'song': 'lagu', 'sorry': 'maaf', 'student': 'murid, siswa',
    'supermarket': 'supermarket', 'table': 'meja', 'tasty': 'enak',
    'taxi': 'taksi', 'tea': 'teh', 'teacher': 'guru', 'telephone': 'telepon',
    'television': 'televisi', 'ten': 'sepuluh', 'thank you': 'terima kasih',
    'there': 'di sana', 'they': 'mereka', 'this': 'ini',
    'this year': 'tahun ini', 'thousand': 'seribu', 'three': 'tiga',
    'time': 'waktu', 'to arrive': 'tiba', 'to ask': 'bertanya',
    'to be': 'adalah', 'to buy': 'membeli', 'to come': 'datang',
    'to cook': 'memasak', 'to do': 'melakukan', 'to drink': 'minum',
    'to drive': 'mengendarai', 'to eat': 'makan', 'to go': 'pergi',
    'to have': 'punya', 'to have, there is': 'ada', 'to know (a fact)': 'tahu',
    'to like': 'suka', 'to listen': 'mendengarkan', 'to live (reside)': 'tinggal',
    'to look for': 'mencari', 'to look, to read': 'melihat, membaca', 'to love': 'cinta',
    'to open': 'membuka', 'to read': 'membaca', 'to rest': 'istirahat',
    'to return': 'kembali', 'to sell': 'menjual', 'to sing': 'bernyanyi',
    'to sleep': 'tidur', 'to speak, to say': 'berbicara, berkata',
    'to study': 'belajar', 'to study, to learn': 'belajar',
    'to want, to think': 'ingin, berpikir', 'to want; to need': 'ingin; butuh',
    'to wear': 'memakai', 'to work; job': 'bekerja; pekerjaan', 'to write': 'menulis',
    'today': 'hari ini', 'tomorrow': 'besok', 'too (excessive)': 'terlalu',
    'train': 'kereta api', 'two': 'dua', 'university': 'universitas',
    'very, rather': 'sangat, cukup', 'water': 'air', 'we': 'kami, kita',
    'weather': 'cuaca', 'week': 'minggu', 'what': 'apa', 'where': 'di mana',
    'which': 'yang mana', 'who': 'siapa', 'year': 'tahun', 'years old': 'tahun',
    'yesterday': 'kemarin', 'you': 'kamu, Anda', 'you (plural)': 'kalian',
    "you're welcome": 'sama-sama', 'younger brother': 'adik laki-laki',
    'younger sister': 'adik perempuan', 'zero': 'nol',
}

# ─── SIMPLIFIED CHINESE ──────────────────────────────────────────────────
ZH_HANS = {
    '"and...?" particle': '"那…呢？"语气词', 'China': '中国', 'Chinese (written)': '中文（书面）',
    'Chinese character': '汉字', 'Chinese language': '汉语', 'I, me': '我',
    'Sunday': '星期天', 'a few, some': '一些', 'a little': '一点儿',
    'after, behind': '后面', 'afternoon': '下午', 'again': '又，再',
    'airplane': '飞机', 'all': '都，全部', 'also': '也', 'and, with': '和',
    'apple': '苹果', 'before, in front': '前面', 'big': '大', 'book': '书',
    'bookstore': '书店', 'boyfriend': '男朋友', 'bread': '面包',
    'breakfast': '早餐', 'busy': '忙', 'can, to be able to': '能',
    'can, to know how to': '会', 'car, vehicle': '车', 'cat': '猫',
    'chair': '椅子', 'cheap': '便宜', 'child': '孩子', 'cinema': '电影院',
    'class, lesson': '课', 'classmate': '同学', 'clothing': '衣服',
    'cold': '冷', 'company': '公司', 'computer': '电脑', 'cooked rice': '米饭',
    'country': '国家', 'cup, glass': '杯子', 'dad': '爸爸', 'daughter': '女儿',
    'dinner': '晚饭', 'doctor': '医生', 'dog': '狗', 'dumplings': '饺子',
    'early': '早', 'egg': '鸡蛋', 'eight': '八', 'evening': '晚上',
    'everyone': '大家', 'expensive': '贵', 'family members': '家人',
    'female': '女', 'film': '电影', 'five': '五', 'four': '四',
    'friend': '朋友', 'fruit': '水果', 'fun': '好玩',
    'girlfriend': '女朋友', 'good, well': '好', 'goodbye': '再见',
    'half': '半', 'happy, glad': '高兴', 'he': '他', 'hello': '你好',
    'here': '这里', 'home, family': '家', 'hospital': '医院', 'hot': '热',
    'how': '怎么', 'how much': '多少', 'hundred': '百', 'inside': '里面',
    'last year': '去年', 'lunch': '午饭', 'male': '男', 'many, much': '多',
    'milk': '牛奶', 'mobile phone': '手机', 'mom': '妈妈', 'money': '钱',
    'month, moon': '月', 'new': '新', 'next year': '明年', 'nine': '九',
    'noodles': '面条', 'noon': '中午', 'not': '不', 'now': '现在',
    'one': '一', 'outside': '外面', 'person, people': '人', 'rain': '雨',
    'really': '真的', 'restaurant, hotel': '饭店', 'room': '房间',
    'school': '学校', 'seven': '七', 'she': '她', 'shop': '商店',
    'six': '六', 'small': '小', 'snow': '雪', 'son': '儿子', 'song': '歌',
    'sorry': '对不起', 'student': '学生', 'supermarket': '超市',
    'table': '桌子', 'tasty': '好吃', 'taxi': '出租车', 'tea': '茶',
    'teacher': '老师', 'telephone': '电话', 'television': '电视',
    'ten': '十', 'thank you': '谢谢', 'there': '那里', 'they': '他们',
    'this': '这', 'this year': '今年', 'thousand': '千', 'three': '三',
    'time': '时间', 'to arrive': '到', 'to ask': '问', 'to be': '是',
    'to buy': '买', 'to come': '来', 'to cook': '做饭', 'to do': '做',
    'to drink': '喝', 'to drive': '开车', 'to eat': '吃', 'to go': '去',
    'to have': '有', 'to have, there is': '有', 'to know (a fact)': '知道',
    'to like': '喜欢', 'to listen': '听', 'to live (reside)': '住',
    'to look for': '找', 'to love': '爱', 'to open': '开', 'to read': '读',
    'to rest': '休息', 'to return': '回', 'to sell': '卖', 'to sing': '唱',
    'to sleep': '睡觉', 'to speak, to say': '说', 'to study': '学习',
    'to want, to think': '想', 'to want; to need': '要', 'to wear': '穿',
    'to work; job': '工作', 'to write': '写', 'today': '今天',
    'tomorrow': '明天', 'too (excessive)': '太', 'train': '火车',
    'two': '二', 'university': '大学', 'very, rather': '很',
    'water': '水', 'we': '我们', 'weather': '天气', 'week': '星期',
    'what': '什么', 'where': '哪里', 'which': '哪', 'who': '谁',
    'year': '年', 'years old': '岁', 'yesterday': '昨天', 'you': '你',
    'you (plural)': '你们', 'you (polite)': '您', "you're welcome": '不客气',
    'younger brother': '弟弟', 'younger sister': '妹妹', 'zero': '零',
}

# zh-Hant uses same as zh-Hans for most — Traditional forms handled at character level
ZH_HANT = dict(ZH_HANS)
ZH_HANT.update({
    'Chinese (written)': '中文（書面）', 'airplane': '飛機', 'bookstore': '書店',
    'breakfast': '早餐', 'computer': '電腦', 'everyone': '大家', 'film': '電影',
    'mobile phone': '手機', 'television': '電視', 'telephone': '電話',
    'cinema': '電影院', 'cooked rice': '米飯', 'noodles': '麵條',
    'train': '火車', 'hospital': '醫院', 'doctor': '醫生',
})

# ─── HINDI ───────────────────────────────────────────────────────────────
HI = {
    'China': 'चीन', 'Chinese language': 'चीनी भाषा', 'I, me': 'मैं',
    'Sunday': 'रविवार', 'a little': 'थोड़ा', 'after, behind': 'बाद, पीछे',
    'afternoon': 'दोपहर', 'again': 'फिर', 'airplane': 'हवाई जहाज',
    'all': 'सब', 'also': 'भी', 'apple': 'सेब', 'big': 'बड़ा',
    'book': 'किताब', 'bread': 'रोटी', 'breakfast': 'नाश्ता', 'busy': 'व्यस्त',
    'car, vehicle': 'गाड़ी', 'cat': 'बिल्ली', 'chair': 'कुर्सी',
    'cheap': 'सस्ता', 'child': 'बच्चा', 'cold': 'ठंडा', 'company': 'कंपनी',
    'computer': 'कंप्यूटर', 'cooked rice': 'चावल', 'country': 'देश',
    'dad': 'पापा', 'daughter': 'बेटी', 'dinner': 'रात का खाना',
    'doctor': 'डॉक्टर', 'dog': 'कुत्ता', 'early': 'जल्दी', 'egg': 'अंडा',
    'eight': 'आठ', 'evening': 'शाम', 'everyone': 'सभी', 'expensive': 'महंगा',
    'family members': 'परिवार के सदस्य', 'female': 'महिला', 'film': 'फिल्म',
    'five': 'पाँच', 'four': 'चार', 'friend': 'दोस्त', 'fruit': 'फल',
    'good, well': 'अच्छा', 'goodbye': 'अलविदा', 'half': 'आधा',
    'happy, glad': 'खुश', 'he': 'वह (पुरुष)', 'hello': 'नमस्ते',
    'here': 'यहाँ', 'home, family': 'घर, परिवार', 'hospital': 'अस्पताल',
    'hot': 'गर्म', 'how': 'कैसे', 'how much': 'कितना', 'hundred': 'सौ',
    'inside': 'अंदर', 'last year': 'पिछला साल', 'lunch': 'दोपहर का खाना',
    'male': 'पुरुष', 'many, much': 'बहुत', 'milk': 'दूध',
    'mobile phone': 'मोबाइल फोन', 'mom': 'माँ', 'money': 'पैसा',
    'month, moon': 'महीना, चाँद', 'new': 'नया', 'next year': 'अगला साल',
    'nine': 'नौ', 'noodles': 'नूडल्स', 'noon': 'दोपहर', 'not': 'नहीं',
    'now': 'अभी', 'one': 'एक', 'outside': 'बाहर', 'person, people': 'व्यक्ति, लोग',
    'rain': 'बारिश', 'really': 'सच में', 'restaurant, hotel': 'रेस्तरां, होटल',
    'room': 'कमरा', 'school': 'स्कूल', 'seven': 'सात', 'she': 'वह (महिला)',
    'shop': 'दुकान', 'six': 'छह', 'small': 'छोटा', 'snow': 'बर्फ',
    'son': 'बेटा', 'song': 'गाना', 'sorry': 'माफ कीजिए', 'student': 'छात्र',
    'supermarket': 'सुपरमार्केट', 'table': 'मेज', 'tasty': 'स्वादिष्ट',
    'taxi': 'टैक्सी', 'tea': 'चाय', 'teacher': 'शिक्षक', 'telephone': 'फोन',
    'television': 'टेलीविज़न', 'ten': 'दस', 'thank you': 'धन्यवाद',
    'there': 'वहाँ', 'they': 'वे', 'this': 'यह', 'this year': 'इस साल',
    'thousand': 'हजार', 'three': 'तीन', 'time': 'समय', 'to arrive': 'पहुँचना',
    'to ask': 'पूछना', 'to be': 'होना', 'to buy': 'खरीदना', 'to come': 'आना',
    'to cook': 'खाना बनाना', 'to do': 'करना', 'to drink': 'पीना',
    'to drive': 'गाड़ी चलाना', 'to eat': 'खाना', 'to go': 'जाना',
    'to have': 'रखना', 'to have, there is': 'है, होना', 'to know (a fact)': 'जानना',
    'to like': 'पसंद करना', 'to listen': 'सुनना', 'to live (reside)': 'रहना',
    'to look for': 'ढूँढना', 'to love': 'प्यार करना', 'to open': 'खोलना',
    'to read': 'पढ़ना', 'to rest': 'आराम करना', 'to return': 'लौटना',
    'to sell': 'बेचना', 'to sing': 'गाना गाना', 'to sleep': 'सोना',
    'to speak, to say': 'बोलना, कहना', 'to study': 'पढ़ाई करना',
    'to want, to think': 'चाहना, सोचना', 'to wear': 'पहनना',
    'to work; job': 'काम करना; नौकरी', 'to write': 'लिखना',
    'today': 'आज', 'tomorrow': 'कल', 'too (excessive)': 'बहुत ज़्यादा',
    'train': 'ट्रेन', 'two': 'दो', 'university': 'विश्वविद्यालय',
    'very, rather': 'बहुत', 'water': 'पानी', 'we': 'हम', 'weather': 'मौसम',
    'week': 'हफ्ता', 'what': 'क्या', 'where': 'कहाँ', 'which': 'कौन सा',
    'who': 'कौन', 'year': 'साल', 'years old': 'साल (उम्र)',
    'yesterday': 'कल (बीता)', 'you': 'तुम', 'you (plural)': 'आप सब',
    'you (polite)': 'आप', "you're welcome": 'कोई बात नहीं',
    'younger brother': 'छोटा भाई', 'younger sister': 'छोटी बहन', 'zero': 'शून्य',
}

# ─── ARABIC ──────────────────────────────────────────────────────────────
AR = {
    'China': 'الصين', 'Chinese language': 'اللغة الصينية', 'I, me': 'أنا',
    'Sunday': 'الأحد', 'a little': 'قليلاً', 'after, behind': 'بعد، خلف',
    'afternoon': 'بعد الظهر', 'again': 'مرة أخرى', 'airplane': 'طائرة',
    'all': 'الكل', 'also': 'أيضاً', 'apple': 'تفاحة', 'big': 'كبير',
    'book': 'كتاب', 'bread': 'خبز', 'breakfast': 'فطور', 'busy': 'مشغول',
    'car, vehicle': 'سيارة', 'cat': 'قطة', 'chair': 'كرسي', 'cheap': 'رخيص',
    'child': 'طفل', 'cold': 'بارد', 'company': 'شركة', 'computer': 'حاسوب',
    'cooked rice': 'أرز مطبوخ', 'country': 'بلد', 'dad': 'أب',
    'daughter': 'ابنة', 'dinner': 'عشاء', 'doctor': 'طبيب', 'dog': 'كلب',
    'early': 'مبكراً', 'egg': 'بيضة', 'eight': 'ثمانية', 'evening': 'مساء',
    'everyone': 'الجميع', 'expensive': 'غالي', 'family members': 'أفراد العائلة',
    'female': 'أنثى', 'film': 'فيلم', 'five': 'خمسة', 'four': 'أربعة',
    'friend': 'صديق', 'fruit': 'فاكهة', 'good, well': 'جيد', 'goodbye': 'مع السلامة',
    'half': 'نصف', 'happy, glad': 'سعيد', 'he': 'هو', 'hello': 'مرحباً',
    'here': 'هنا', 'home, family': 'بيت، عائلة', 'hospital': 'مستشفى',
    'hot': 'حار', 'how': 'كيف', 'how much': 'كم', 'hundred': 'مئة',
    'inside': 'داخل', 'male': 'ذكر', 'many, much': 'كثير', 'milk': 'حليب',
    'mobile phone': 'هاتف محمول', 'mom': 'أم', 'money': 'مال',
    'month, moon': 'شهر، قمر', 'new': 'جديد', 'nine': 'تسعة',
    'noodles': 'نودلز', 'noon': 'ظهر', 'not': 'لا، ليس', 'now': 'الآن',
    'one': 'واحد', 'outside': 'خارج', 'person, people': 'شخص، ناس',
    'rain': 'مطر', 'really': 'حقاً', 'restaurant, hotel': 'مطعم، فندق',
    'room': 'غرفة', 'school': 'مدرسة', 'seven': 'سبعة', 'she': 'هي',
    'shop': 'متجر', 'six': 'ستة', 'small': 'صغير', 'snow': 'ثلج',
    'son': 'ابن', 'song': 'أغنية', 'sorry': 'آسف', 'student': 'طالب',
    'supermarket': 'سوبرماركت', 'table': 'طاولة', 'tasty': 'لذيذ',
    'taxi': 'تاكسي', 'tea': 'شاي', 'teacher': 'معلم', 'telephone': 'هاتف',
    'television': 'تلفزيون', 'ten': 'عشرة', 'thank you': 'شكراً',
    'there': 'هناك', 'they': 'هم', 'this': 'هذا', 'thousand': 'ألف',
    'three': 'ثلاثة', 'time': 'وقت', 'to arrive': 'يصل', 'to ask': 'يسأل',
    'to be': 'يكون', 'to buy': 'يشتري', 'to come': 'يأتي',
    'to cook': 'يطبخ', 'to do': 'يفعل', 'to drink': 'يشرب',
    'to eat': 'يأكل', 'to go': 'يذهب', 'to have': 'يملك',
    'to have, there is': 'يوجد', 'to know (a fact)': 'يعرف', 'to like': 'يحب',
    'to listen': 'يستمع', 'to live (reside)': 'يسكن', 'to love': 'يحب (عشق)',
    'to open': 'يفتح', 'to read': 'يقرأ', 'to rest': 'يستريح',
    'to return': 'يعود', 'to sell': 'يبيع', 'to sing': 'يغني',
    'to sleep': 'ينام', 'to speak, to say': 'يتكلم، يقول', 'to study': 'يدرس',
    'to want, to think': 'يريد، يفكر', 'to wear': 'يلبس',
    'to work; job': 'يعمل؛ عمل', 'to write': 'يكتب', 'today': 'اليوم',
    'tomorrow': 'غداً', 'too (excessive)': 'جداً', 'train': 'قطار',
    'two': 'اثنان', 'university': 'جامعة', 'very, rather': 'جداً، إلى حد ما',
    'water': 'ماء', 'we': 'نحن', 'weather': 'طقس', 'week': 'أسبوع',
    'what': 'ماذا', 'where': 'أين', 'which': 'أي', 'who': 'من',
    'year': 'سنة', 'years old': 'سنة (عمر)', 'yesterday': 'أمس',
    'you': 'أنت', 'you (plural)': 'أنتم', "you're welcome": 'عفواً',
    'younger brother': 'أخ أصغر', 'younger sister': 'أخت أصغر', 'zero': 'صفر',
}

# ─── POLISH ──────────────────────────────────────────────────────────────
PL = {
    'China': 'Chiny', 'Chinese language': 'język chiński', 'I, me': 'ja',
    'a little': 'trochę', 'big': 'duży', 'book': 'książka', 'car, vehicle': 'samochód',
    'cat': 'kot', 'child': 'dziecko', 'cold': 'zimno', 'dad': 'tata',
    'dog': 'pies', 'eight': 'osiem', 'five': 'pięć', 'four': 'cztery',
    'friend': 'przyjaciel', 'good, well': 'dobrze', 'he': 'on', 'hello': 'cześć',
    'hot': 'gorąco', 'hundred': 'sto', 'money': 'pieniądze', 'mom': 'mama',
    'new': 'nowy', 'nine': 'dziewięć', 'one': 'jeden', 'rain': 'deszcz',
    'school': 'szkoła', 'seven': 'siedem', 'she': 'ona', 'six': 'sześć',
    'small': 'mały', 'snow': 'śnieg', 'student': 'student', 'tea': 'herbata',
    'teacher': 'nauczyciel', 'ten': 'dziesięć', 'thank you': 'dziękuję',
    'this': 'to', 'three': 'trzy', 'two': 'dwa', 'water': 'woda',
    'year': 'rok', 'you': 'ty', 'zero': 'zero', 'to be': 'być',
    'to eat': 'jeść', 'to drink': 'pić', 'to go': 'iść', 'to have': 'mieć',
    'to read': 'czytać', 'to sleep': 'spać', 'to write': 'pisać',
    'to love': 'kochać', 'today': 'dzisiaj', 'tomorrow': 'jutro',
    'yesterday': 'wczoraj', 'person, people': 'osoba, ludzie',
}

RO = {
    'China': 'China', 'Chinese language': 'limba chineză', 'I, me': 'eu',
    'big': 'mare', 'book': 'carte', 'cat': 'pisică', 'child': 'copil',
    'cold': 'frig', 'dad': 'tata', 'dog': 'câine', 'friend': 'prieten',
    'good, well': 'bine', 'he': 'el', 'hello': 'bună', 'mom': 'mama',
    'new': 'nou', 'one': 'unu', 'school': 'școală', 'she': 'ea',
    'small': 'mic', 'student': 'student', 'tea': 'ceai', 'teacher': 'profesor',
    'thank you': 'mulțumesc', 'this': 'acesta', 'three': 'trei', 'two': 'doi',
    'water': 'apă', 'year': 'an', 'you': 'tu', 'zero': 'zero',
    'to be': 'a fi', 'to eat': 'a mânca', 'to go': 'a merge', 'to love': 'a iubi',
    'today': 'azi', 'tomorrow': 'mâine', 'yesterday': 'ieri',
}

UK = {
    'China': 'Китай', 'Chinese language': 'китайська мова', 'I, me': 'я',
    'big': 'великий', 'book': 'книга', 'cat': 'кіт', 'child': 'дитина',
    'cold': 'холодно', 'dad': 'тато', 'dog': 'собака', 'friend': 'друг',
    'good, well': 'добре', 'he': 'він', 'hello': 'привіт', 'mom': 'мама',
    'new': 'новий', 'one': 'один', 'school': 'школа', 'she': 'вона',
    'small': 'малий', 'student': 'студент', 'tea': 'чай', 'teacher': 'вчитель',
    'thank you': 'дякую', 'this': 'це', 'three': 'три', 'two': 'два',
    'water': 'вода', 'year': 'рік', 'you': 'ти', 'zero': 'нуль',
    'to be': 'бути', 'to eat': 'їсти', 'to go': 'йти', 'to love': 'любити',
    'today': 'сьогодні', 'tomorrow': 'завтра', 'yesterday': 'вчора',
}

ALL_LOCALES = {
    'ja': JA, 'ko': KO, 'vi': VI, 'th': TH,
    'zh-Hans': ZH_HANS, 'zh-Hant': ZH_HANT,
    'id': ID, 'hi': HI, 'ar': AR,
    'pl': PL, 'ro': RO, 'uk': UK,
}

# ─── INSERT ──────────────────────────────────────────────────────────────
total = 0
for locale, trans_dict in ALL_LOCALES.items():
    rows = []
    for v in vocab_en:
        en_meaning = v['meaning']
        translated = trans_dict.get(en_meaning, en_meaning)
        rows.append({
            'vocabulary_id': v['vocabulary_id'],
            'locale': locale,
            'meaning': translated,
            'example_sentence': v.get('example_sentence', ''),
        })

    for i in range(0, len(rows), 100):
        batch = rows[i:i+100]
        status, n = supa_post('vocabulary_translations', batch)
        total += n
        print(f"  {locale}: batch {i//100+1} → {n} rows (status={status})")

print(f"\n{'='*60}")
print(f"Total vocabulary translations inserted: {total}")
print(f"{'='*60}")
