#!/usr/bin/env python3
"""
Insert character_translations for Asian + remaining locales:
ja, ko, vi, th, zh-Hans, zh-Hant, id, hi, ar, pl, ro, uk
"""
import json, sys
from urllib.request import Request, urlopen
from urllib.error import HTTPError

URL = 'https://gmpjkoajhhwvxwsdohll.supabase.co'
KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtcGprb2FqaGh3dnh3c2RvaGxsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4Mjk4Mzk0NSwiZXhwIjoyMDk4NTU5OTQ1fQ.iHoqQdpjq3_vCMuuHEs9Y9in_lpKQ_cCRaI3EtJ6tKc'

def supa_get(table, params=''):
    req = Request(f'{URL}/rest/v1/{table}?{params}', headers={'apikey': KEY, 'Authorization': f'Bearer {KEY}'})
    return json.loads(urlopen(req).read())

def supa_post(table, rows):
    req = Request(f'{URL}/rest/v1/{table}',
        data=json.dumps(rows).encode('utf-8'),
        headers={
            'apikey': KEY, 'Authorization': f'Bearer {KEY}',
            'Content-Type': 'application/json',
            'Prefer': 'resolution=ignore-duplicates',
        }, method='POST')
    try:
        resp = urlopen(req)
        return resp.status, len(rows)
    except HTTPError as e:
        body = e.read().decode()[:300]
        print(f"    POST error {e.code}: {body}")
        return e.code, 0

char_en = supa_get('character_translations', 'select=character_id,meaning,mnemonic&locale=eq.en&order=character_id&limit=500')
print(f"Loaded {len(char_en)} EN character items")

# ─── JAPANESE ───────────────────────────────────────────────────────────
JA = {
    'Chinese, Han': '中国、漢', 'after, behind': '後ろ、後', 'again': 'また',
    'air, energy': '空気、気', 'all, both': '全部、両方', 'also': 'も',
    'and, with, harmony': 'と、和', 'appearance, type': '外見、タイプ',
    'apple (in 苹果)': 'りんご（苹果の）', 'at, in': '～に、～で',
    'bed': 'ベッド', 'between, space': '間', 'big, large': '大きい',
    'book': '本', 'brain': '脳', 'breath, rest': '息、休み',
    'bright, light': '明るい、光', 'bright, tomorrow': '明るい、明日',
    'busy': '忙しい', 'can, ability': '能力、できる', 'can, meeting': '会、できる',
    'can, possible': 'できる、可能', 'car, vehicle': '車',
    'cat': '猫', 'chair': '椅子', 'character, word': '文字',
    'chicken': '鶏', 'child': '子供', 'child, son': '子、息子',
    'class, group': 'クラス、グループ', 'class, lesson': '授業',
    'clock, bell': '時計、鐘', 'close, relationship': '親しい、関係',
    'clothing': '服', 'clothing, serve': '服、仕える', 'cold': '寒い',
    'commerce': '商業', 'completed action particle': '完了の助詞',
    'convenient': '便利', 'cooked rice, meal': 'ご飯、食事',
    'correct, toward': '正しい、～に向かって', 'courtyard, hospital': '庭、病院',
    'cow, ox': '牛', 'cup, glass': 'コップ', 'day, sun': '日、太陽',
    'divide, minute': '分ける、分', 'doctor, medicine': '医者、薬',
    'dog': '犬', 'down, below': '下', 'dumpling': '餃子',
    'early, morning': '早い、朝', 'east': '東', 'egg': '卵',
    'eight': '八', 'electricity': '電気', 'evening, late': '夜、遅い',
    'exceed, super': '超える', 'expensive, precious': '高い、貴重',
    'face, noodles': '顔、麺', 'family, home': '家族、家',
    'father, dad': '父', 'feel, sense': '感じる', 'few, young': '少ない、若い',
    'fire': '火', 'first, before': '最初、前', 'five': '五',
    'four': '四', 'friend': '友達', 'fruit, result': '果物、結果',
    'general measure word': '一般量詞', 'get, must': '得る、必須',
    'good, well': '良い', 'grandmother, milk': '祖母、牛乳',
    'guest, customer': '客', 'half': '半分', 'hand': '手',
    'happy, joyful': '嬉しい', 'he, him': '彼', 'hello, to feed': 'もしもし、食べさせる',
    'hit, play': '打つ、遊ぶ', 'hot': '暑い', 'how': 'どう',
    'how many, several': 'いくつ', 'hundred': '百', 'illness, sick': '病気',
    'in front, before': '前', 'inside, in': '中', 'interest, excitement': '興味、興奮',
    'it': 'それ', 'joy, happy': '喜び、幸せ', 'know, recognize': '知る、認識する',
    'language': '言語', 'look, see': '見る', 'love': '愛',
    'machine, airplane': '機械、飛行機', 'man, male': '男',
    'manage, company': '管理、会社', 'many, much': '多い',
    'market, city': '市場、市', 'matter, thing': '事', 'money': 'お金',
    'moon, month': '月', 'mother': '母', 'mouth': '口', 'name': '名前',
    'new': '新しい', 'nine': '九', 'noon': '正午', 'not have': 'ない',
    'not, no': 'いいえ、ない', 'not, non-': '非、不', 'now, present': '今',
    'number': '番号', 'often, usual': 'よく、普通', 'old': '古い、老いた',
    'older brother': '兄', 'older sister': '姉', 'one': '一', 'only': 'だけ',
    'open, start': '開く、始める', 'ordinal prefix': '第～',
    'origin, book': '元、本', 'outside': '外', 'package, wrap': '包む',
    'particle (what about?)': '助詞（は？）', 'period, date': '期間、日付',
    'person, people': '人', 'piece, item': '個、品', 'piece, lump': '塊',
    'please, invite': 'どうぞ、招待する', 'plural suffix': '～たち',
    "point, o'clock": '点、～時', 'possessive particle': '～の',
    'pretty, float': 'きれい、浮く', 'public, fair': '公共、公平',
    'question particle': '疑問助詞', 'rain': '雨', 'recognize': '認識する',
    'rice': '米', 'right, correct': '右、正しい', 'rise, start': '起きる、始まる',
    'road, way': '道', 'room, house': '部屋、家', 'same': '同じ',
    'say, speak': '言う、話す', 'scholar, soldier': '学者、兵士',
    'school': '学校', 'see, meet': '見る、会う', 'seven': '七',
    'shadow, movie': '影、映画', 'she, her': '彼女', 'shop, store': '店',
    'side, edge': '横、端', 'six': '六', 'sky, day': '空、日',
    'small': '小さい', 'snow': '雪', 'some, a few': 'いくつか', 'song': '歌',
    'speech, language': '話、言語', 'star': '星', 'still, also': 'まだ、も',
    'strip, measure word': '条、量詞', 'study, practice': '勉強、練習',
    'suggestion particle': '提案の助詞', 'suitable, cheap': '適切、安い',
    'system, link': '系統、つながり', 'table, desk': 'テーブル、机',
    'tall, high': '高い', 'tea': 'お茶', 'teacher, master': '先生',
    'ten': '十', 'text, culture': '文、文化', 'thank you': 'ありがとう',
    'that': 'あれ', 'think, want': '思う、欲しい', 'this': 'これ',
    'thousand': '千', 'three': '三', 'time, hour': '時間',
    'to arrive': '着く', 'to ask': '聞く', 'to buy': '買う',
    'to call': '呼ぶ', 'to come': '来る', 'to do, make': 'する、作る',
    'to do, to work': 'する、働く', 'to drink': '飲む', 'to eat': '食べる',
    'to fly': '飛ぶ', 'to give': 'あげる', 'to go': '行く',
    'to go out': '出かける', 'to have': '持っている', 'to know': '知る',
    'to listen': '聞く', 'to live, reside': '住む', 'to look for': '探す',
    'to play': '遊ぶ', 'to read': '読む', 'to rent': '借りる',
    'to rest': '休む', 'to return': '帰る', 'to sell': '売る',
    'to sing': '歌う', 'to sit': '座る', 'to sleep': '寝る',
    'to wait, moment': '待つ、瞬間', 'to wear': '着る', 'to write': '書く',
    'today, now': '今日、今', 'too, very': 'も、とても', 'topic, question': '話題、質問',
    'true, really': '本当に', 'two': '二', 'two (quantity)': '二（数量）',
    'up, above': '上', 'vegetable, dish': '野菜、料理', 'very': 'とても',
    'want, need': '欲しい、必要', 'watch, vision': '見る、視覚',
    'water': '水', 'west': '西', 'what (in 什么)': '何（什么の）',
    'where, which': 'どこ、どの', 'white': '白い', 'who': '誰',
    'with, by, since': '～と、～で、～から', 'woman': '女性',
    'work, worker': '仕事、労働者', 'year': '年', 'year, age': '年、年齢',
    'yesterday': '昨日', 'you': 'あなた', 'you (formal)': 'あなた（丁寧）',
    'younger brother': '弟', 'younger sister': '妹', 'yuan, origin': '元',
    'zero': '零',
}

# ─── KOREAN ─────────────────────────────────────────────────────────────
KO = {
    'Chinese, Han': '중국, 한', 'after, behind': '후, 뒤', 'again': '또',
    'air, energy': '공기, 기', 'all, both': '모두, 둘 다', 'also': '도',
    'and, with, harmony': '그리고, 화합', 'appearance, type': '외모, 유형',
    'apple (in 苹果)': '사과 (苹果)', 'at, in': '~에',
    'bed': '침대', 'between, space': '사이, 공간', 'big, large': '큰',
    'book': '책', 'brain': '뇌', 'breath, rest': '숨, 쉼',
    'bright, light': '밝은, 빛', 'bright, tomorrow': '밝은, 내일',
    'busy': '바쁜', 'can, ability': '능력, ~할 수 있다', 'can, meeting': '회의, ~할 수 있다',
    'can, possible': '가능한', 'car, vehicle': '차, 자동차',
    'cat': '고양이', 'chair': '의자', 'character, word': '글자',
    'chicken': '닭', 'child': '아이', 'child, son': '아이, 아들',
    'class, group': '반, 그룹', 'class, lesson': '수업',
    'clock, bell': '시계, 종', 'close, relationship': '가까운, 관계',
    'clothing': '옷', 'clothing, serve': '옷, 봉사하다', 'cold': '추운',
    'commerce': '상업', 'completed action particle': '완료 조사',
    'convenient': '편리한', 'cooked rice, meal': '밥, 식사',
    'correct, toward': '맞다, ~를 향해', 'courtyard, hospital': '마당, 병원',
    'cow, ox': '소', 'cup, glass': '컵, 잔', 'day, sun': '날, 해',
    'divide, minute': '나누다, 분', 'doctor, medicine': '의사, 약',
    'dog': '개', 'down, below': '아래', 'dumpling': '만두',
    'early, morning': '이른, 아침', 'east': '동쪽', 'egg': '계란',
    'eight': '팔', 'electricity': '전기', 'evening, late': '저녁, 늦은',
    'exceed, super': '초과하다', 'expensive, precious': '비싼, 귀중한',
    'face, noodles': '얼굴, 국수', 'family, home': '가족, 집',
    'father, dad': '아버지', 'feel, sense': '느끼다', 'few, young': '적은, 젊은',
    'fire': '불', 'first, before': '먼저, 전', 'five': '오',
    'four': '사', 'friend': '친구', 'fruit, result': '과일, 결과',
    'general measure word': '일반 분류사', 'get, must': '얻다, ~해야 한다',
    'good, well': '좋은', 'grandmother, milk': '할머니, 우유',
    'guest, customer': '손님', 'half': '반', 'hand': '손',
    'happy, joyful': '행복한', 'he, him': '그', 'hello, to feed': '여보세요, 먹이다',
    'hit, play': '치다, 놀다', 'hot': '더운', 'how': '어떻게',
    'how many, several': '몇', 'hundred': '백', 'illness, sick': '병, 아프다',
    'in front, before': '앞', 'inside, in': '안', 'interest, excitement': '흥미, 흥분',
    'it': '그것', 'joy, happy': '기쁨, 행복', 'know, recognize': '알다, 인식하다',
    'language': '언어', 'look, see': '보다', 'love': '사랑',
    'machine, airplane': '기계, 비행기', 'man, male': '남자',
    'manage, company': '관리, 회사', 'many, much': '많은',
    'market, city': '시장, 도시', 'matter, thing': '일', 'money': '돈',
    'moon, month': '달', 'mother': '어머니', 'mouth': '입', 'name': '이름',
    'new': '새로운', 'nine': '구', 'noon': '정오', 'not have': '없다',
    'not, no': '아니요', 'not, non-': '비, 불', 'now, present': '지금',
    'number': '번호', 'often, usual': '자주, 보통', 'old': '오래된, 늙은',
    'older brother': '형/오빠', 'older sister': '누나/언니', 'one': '일', 'only': '만',
    'open, start': '열다, 시작하다', 'ordinal prefix': '제~',
    'origin, book': '원래, 책', 'outside': '밖', 'package, wrap': '싸다',
    'particle (what about?)': '조사 (~은/는?)', 'period, date': '기간, 날짜',
    'person, people': '사람', 'piece, item': '개, 물건', 'piece, lump': '덩어리',
    'please, invite': '~해주세요, 초대하다', 'plural suffix': '~들',
    "point, o'clock": '점, ~시', 'possessive particle': '~의',
    'pretty, float': '예쁜, 뜨다', 'public, fair': '공공, 공정',
    'question particle': '의문 조사', 'rain': '비', 'recognize': '인식하다',
    'rice': '쌀', 'right, correct': '오른쪽, 맞다', 'rise, start': '일어나다, 시작하다',
    'road, way': '길', 'room, house': '방, 집', 'same': '같은',
    'say, speak': '말하다', 'scholar, soldier': '학자, 군인',
    'school': '학교', 'see, meet': '보다, 만나다', 'seven': '칠',
    'shadow, movie': '그림자, 영화', 'she, her': '그녀', 'shop, store': '가게',
    'side, edge': '옆, 가장자리', 'six': '육', 'sky, day': '하늘, 날',
    'small': '작은', 'snow': '눈', 'some, a few': '몇 개', 'song': '노래',
    'speech, language': '말, 언어', 'star': '별', 'still, also': '아직, 도',
    'strip, measure word': '줄, 분류사', 'study, practice': '공부, 연습',
    'suggestion particle': '제안 조사', 'suitable, cheap': '적합한, 싼',
    'system, link': '체계, 연결', 'table, desk': '탁자, 책상',
    'tall, high': '높은', 'tea': '차', 'teacher, master': '선생님',
    'ten': '십', 'text, culture': '글, 문화', 'thank you': '감사합니다',
    'that': '저것', 'think, want': '생각하다, 원하다', 'this': '이것',
    'thousand': '천', 'three': '삼', 'time, hour': '시간',
    'to arrive': '도착하다', 'to ask': '묻다', 'to buy': '사다',
    'to call': '부르다', 'to come': '오다', 'to do, make': '하다, 만들다',
    'to do, to work': '하다, 일하다', 'to drink': '마시다', 'to eat': '먹다',
    'to fly': '날다', 'to give': '주다', 'to go': '가다',
    'to go out': '나가다', 'to have': '가지다', 'to know': '알다',
    'to listen': '듣다', 'to live, reside': '살다', 'to look for': '찾다',
    'to play': '놀다', 'to read': '읽다', 'to rent': '빌리다',
    'to rest': '쉬다', 'to return': '돌아가다', 'to sell': '팔다',
    'to sing': '노래하다', 'to sit': '앉다', 'to sleep': '자다',
    'to wait, moment': '기다리다, 순간', 'to wear': '입다', 'to write': '쓰다',
    'today, now': '오늘, 지금', 'too, very': '너무, 매우', 'topic, question': '화제, 질문',
    'true, really': '진짜, 정말', 'two': '이', 'two (quantity)': '둘 (수량)',
    'up, above': '위', 'vegetable, dish': '채소, 요리', 'very': '매우',
    'want, need': '원하다, 필요하다', 'watch, vision': '보다, 시력',
    'water': '물', 'west': '서쪽', 'what (in 什么)': '무엇 (什么)',
    'where, which': '어디, 어느', 'white': '흰', 'who': '누구',
    'with, by, since': '~와, ~로, ~부터', 'woman': '여자',
    'work, worker': '일, 노동자', 'year': '년', 'year, age': '년, 나이',
    'yesterday': '어제', 'you': '너', 'you (formal)': '당신 (존칭)',
    'younger brother': '남동생', 'younger sister': '여동생', 'yuan, origin': '위안, 원래',
    'zero': '영',
}

# ─── VIETNAMESE ──────────────────────────────────────────────────────────
VI = {
    'Chinese, Han': 'Trung Quốc, Hán', 'after, behind': 'sau, phía sau', 'again': 'lại',
    'air, energy': 'không khí, khí', 'all, both': 'tất cả, cả hai', 'also': 'cũng',
    'and, with, harmony': 'và, với, hòa hợp', 'appearance, type': 'ngoại hình, loại',
    'apple (in 苹果)': 'táo (trong 苹果)', 'at, in': 'ở, trong',
    'bed': 'giường', 'between, space': 'giữa, không gian', 'big, large': 'to, lớn',
    'book': 'sách', 'brain': 'não', 'breath, rest': 'hơi thở, nghỉ',
    'bright, light': 'sáng, ánh sáng', 'bright, tomorrow': 'sáng, ngày mai',
    'busy': 'bận', 'can, ability': 'năng lực, có thể', 'can, meeting': 'cuộc họp, có thể',
    'can, possible': 'có thể', 'car, vehicle': 'xe',
    'cat': 'mèo', 'chair': 'ghế', 'character, word': 'chữ',
    'chicken': 'gà', 'child': 'trẻ em', 'child, son': 'con, con trai',
    'class, group': 'lớp, nhóm', 'class, lesson': 'lớp học, bài học',
    'clock, bell': 'đồng hồ, chuông', 'close, relationship': 'gần, mối quan hệ',
    'clothing': 'quần áo', 'clothing, serve': 'quần áo, phục vụ', 'cold': 'lạnh',
    'commerce': 'thương mại', 'completed action particle': 'trợ từ hoàn thành',
    'convenient': 'tiện lợi', 'cooked rice, meal': 'cơm, bữa ăn',
    'correct, toward': 'đúng, hướng về', 'courtyard, hospital': 'sân, bệnh viện',
    'cow, ox': 'bò', 'cup, glass': 'cốc, ly', 'day, sun': 'ngày, mặt trời',
    'divide, minute': 'chia, phút', 'doctor, medicine': 'bác sĩ, thuốc',
    'dog': 'chó', 'down, below': 'dưới', 'dumpling': 'sủi cảo',
    'early, morning': 'sớm, buổi sáng', 'east': 'đông', 'egg': 'trứng',
    'eight': 'tám', 'electricity': 'điện', 'evening, late': 'tối, muộn',
    'exceed, super': 'vượt quá', 'expensive, precious': 'đắt, quý',
    'face, noodles': 'mặt, mì', 'family, home': 'gia đình, nhà',
    'father, dad': 'bố', 'feel, sense': 'cảm giác', 'few, young': 'ít, trẻ',
    'fire': 'lửa', 'first, before': 'đầu tiên, trước', 'five': 'năm',
    'four': 'bốn', 'friend': 'bạn', 'fruit, result': 'quả, kết quả',
    'general measure word': 'lượng từ chung', 'get, must': 'được, phải',
    'good, well': 'tốt', 'grandmother, milk': 'bà, sữa',
    'guest, customer': 'khách', 'half': 'nửa', 'hand': 'tay',
    'happy, joyful': 'vui, hạnh phúc', 'he, him': 'anh ấy', 'hello, to feed': 'xin chào, cho ăn',
    'hit, play': 'đánh, chơi', 'hot': 'nóng', 'how': 'thế nào',
    'how many, several': 'mấy', 'hundred': 'trăm', 'illness, sick': 'bệnh',
    'in front, before': 'trước', 'inside, in': 'bên trong', 'interest, excitement': 'hứng thú',
    'it': 'nó', 'joy, happy': 'niềm vui, hạnh phúc', 'know, recognize': 'biết, nhận ra',
    'language': 'ngôn ngữ', 'look, see': 'nhìn, thấy', 'love': 'tình yêu',
    'machine, airplane': 'máy, máy bay', 'man, male': 'nam',
    'manage, company': 'quản lý, công ty', 'many, much': 'nhiều',
    'market, city': 'chợ, thành phố', 'matter, thing': 'việc', 'money': 'tiền',
    'moon, month': 'trăng, tháng', 'mother': 'mẹ', 'mouth': 'miệng', 'name': 'tên',
    'new': 'mới', 'nine': 'chín', 'noon': 'trưa', 'not have': 'không có',
    'not, no': 'không', 'not, non-': 'không, phi', 'now, present': 'bây giờ',
    'number': 'số', 'often, usual': 'thường', 'old': 'cũ, già',
    'older brother': 'anh trai', 'older sister': 'chị gái', 'one': 'một', 'only': 'chỉ',
    'open, start': 'mở, bắt đầu', 'ordinal prefix': 'thứ',
    'origin, book': 'gốc, sách', 'outside': 'bên ngoài', 'package, wrap': 'gói',
    'particle (what about?)': 'trợ từ (còn...?)', 'period, date': 'kỳ, ngày',
    'person, people': 'người', 'piece, item': 'miếng, vật', 'piece, lump': 'cục',
    'please, invite': 'mời', 'plural suffix': 'hậu tố số nhiều',
    "point, o'clock": 'điểm, giờ', 'possessive particle': 'trợ từ sở hữu',
    'pretty, float': 'đẹp, nổi', 'public, fair': 'công cộng, công bằng',
    'question particle': 'trợ từ nghi vấn', 'rain': 'mưa', 'recognize': 'nhận ra',
    'rice': 'gạo', 'right, correct': 'phải, đúng', 'rise, start': 'dậy, bắt đầu',
    'road, way': 'đường', 'room, house': 'phòng, nhà', 'same': 'giống',
    'say, speak': 'nói', 'scholar, soldier': 'học giả, lính',
    'school': 'trường', 'see, meet': 'thấy, gặp', 'seven': 'bảy',
    'shadow, movie': 'bóng, phim', 'she, her': 'cô ấy', 'shop, store': 'cửa hàng',
    'side, edge': 'bên, mép', 'six': 'sáu', 'sky, day': 'trời, ngày',
    'small': 'nhỏ', 'snow': 'tuyết', 'some, a few': 'một vài', 'song': 'bài hát',
    'speech, language': 'lời nói, ngôn ngữ', 'star': 'sao', 'still, also': 'vẫn, cũng',
    'strip, measure word': 'dải, lượng từ', 'study, practice': 'học, luyện tập',
    'suggestion particle': 'trợ từ đề nghị', 'suitable, cheap': 'phù hợp, rẻ',
    'system, link': 'hệ thống, liên kết', 'table, desk': 'bàn',
    'tall, high': 'cao', 'tea': 'trà', 'teacher, master': 'giáo viên, thầy',
    'ten': 'mười', 'text, culture': 'văn, văn hóa', 'thank you': 'cảm ơn',
    'that': 'kia', 'think, want': 'nghĩ, muốn', 'this': 'này',
    'thousand': 'nghìn', 'three': 'ba', 'time, hour': 'thời gian, giờ',
    'to arrive': 'đến', 'to ask': 'hỏi', 'to buy': 'mua',
    'to call': 'gọi', 'to come': 'đến', 'to do, make': 'làm',
    'to do, to work': 'làm, làm việc', 'to drink': 'uống', 'to eat': 'ăn',
    'to fly': 'bay', 'to give': 'cho', 'to go': 'đi',
    'to go out': 'ra ngoài', 'to have': 'có', 'to know': 'biết',
    'to listen': 'nghe', 'to live, reside': 'sống, ở', 'to look for': 'tìm',
    'to play': 'chơi', 'to read': 'đọc', 'to rent': 'thuê',
    'to rest': 'nghỉ', 'to return': 'trở về', 'to sell': 'bán',
    'to sing': 'hát', 'to sit': 'ngồi', 'to sleep': 'ngủ',
    'to wait, moment': 'chờ, khoảnh khắc', 'to wear': 'mặc', 'to write': 'viết',
    'today, now': 'hôm nay, bây giờ', 'too, very': 'quá, rất', 'topic, question': 'chủ đề, câu hỏi',
    'true, really': 'thật, thật sự', 'two': 'hai', 'two (quantity)': 'hai (số lượng)',
    'up, above': 'trên', 'vegetable, dish': 'rau, món ăn', 'very': 'rất',
    'want, need': 'muốn, cần', 'watch, vision': 'xem, thị giác',
    'water': 'nước', 'west': 'tây', 'what (in 什么)': 'gì (trong 什么)',
    'where, which': 'đâu, nào', 'white': 'trắng', 'who': 'ai',
    'with, by, since': 'với, bởi, từ', 'woman': 'phụ nữ',
    'work, worker': 'công việc, công nhân', 'year': 'năm', 'year, age': 'năm, tuổi',
    'yesterday': 'hôm qua', 'you': 'bạn', 'you (formal)': 'anh/chị',
    'younger brother': 'em trai', 'younger sister': 'em gái', 'yuan, origin': 'nhân dân tệ, nguồn gốc',
    'zero': 'không',
}

# ─── THAI ────────────────────────────────────────────────────────────────
TH = {
    'Chinese, Han': 'จีน, ฮั่น', 'after, behind': 'หลัง, ข้างหลัง', 'again': 'อีกครั้ง',
    'air, energy': 'อากาศ, พลังงาน', 'all, both': 'ทั้งหมด, ทั้งคู่', 'also': 'ด้วย',
    'big, large': 'ใหญ่', 'book': 'หนังสือ', 'car, vehicle': 'รถ',
    'cat': 'แมว', 'chair': 'เก้าอี้', 'child': 'เด็ก', 'cold': 'เย็น, หนาว',
    'day, sun': 'วัน, ดวงอาทิตย์', 'dog': 'สุนัข', 'eight': 'แปด',
    'family, home': 'ครอบครัว, บ้าน', 'father, dad': 'พ่อ', 'five': 'ห้า',
    'four': 'สี่', 'friend': 'เพื่อน', 'good, well': 'ดี', 'half': 'ครึ่ง',
    'happy, joyful': 'มีความสุข', 'he, him': 'เขา (ผู้ชาย)', 'hot': 'ร้อน',
    'hundred': 'ร้อย', 'love': 'ความรัก', 'man, male': 'ผู้ชาย',
    'many, much': 'มาก', 'money': 'เงิน', 'moon, month': 'พระจันทร์, เดือน',
    'mother': 'แม่', 'mouth': 'ปาก', 'name': 'ชื่อ', 'new': 'ใหม่',
    'nine': 'เก้า', 'noon': 'เที่ยง', 'not, no': 'ไม่', 'now, present': 'ตอนนี้',
    'one': 'หนึ่ง', 'outside': 'ข้างนอก', 'person, people': 'คน',
    'rain': 'ฝน', 'school': 'โรงเรียน', 'seven': 'เจ็ด', 'she, her': 'เขา (ผู้หญิง)',
    'six': 'หก', 'small': 'เล็ก', 'snow': 'หิมะ', 'tea': 'ชา',
    'teacher, master': 'ครู', 'ten': 'สิบ', 'thank you': 'ขอบคุณ',
    'this': 'นี้', 'thousand': 'พัน', 'three': 'สาม', 'two': 'สอง',
    'water': 'น้ำ', 'woman': 'ผู้หญิง', 'year': 'ปี', 'you': 'คุณ',
    'younger brother': 'น้องชาย', 'younger sister': 'น้องสาว', 'zero': 'ศูนย์',
    'to eat': 'กิน', 'to drink': 'ดื่ม', 'to go': 'ไป', 'to come': 'มา',
    'to have': 'มี', 'to read': 'อ่าน', 'to write': 'เขียน', 'to sleep': 'นอน',
    'to buy': 'ซื้อ', 'to sell': 'ขาย', 'to love': 'รัก', 'to ask': 'ถาม',
    'to listen': 'ฟัง', 'to sit': 'นั่ง', 'to sing': 'ร้องเพลง',
    'road, way': 'ถนน, ทาง', 'rice': 'ข้าว', 'egg': 'ไข่', 'fire': 'ไฟ',
    'hand': 'มือ', 'electricity': 'ไฟฟ้า', 'east': 'ตะวันออก', 'west': 'ตะวันตก',
    'white': 'ขาว', 'star': 'ดาว', 'song': 'เพลง',
}

# ─── INDONESIAN ──────────────────────────────────────────────────────────
ID = {
    'Chinese, Han': 'Tionghoa, Han', 'after, behind': 'setelah, belakang', 'again': 'lagi',
    'air, energy': 'udara, energi', 'all, both': 'semua, keduanya', 'also': 'juga',
    'big, large': 'besar', 'book': 'buku', 'car, vehicle': 'mobil, kendaraan',
    'cat': 'kucing', 'chair': 'kursi', 'child': 'anak', 'cold': 'dingin',
    'day, sun': 'hari, matahari', 'dog': 'anjing', 'eight': 'delapan',
    'family, home': 'keluarga, rumah', 'father, dad': 'ayah', 'five': 'lima',
    'four': 'empat', 'friend': 'teman', 'good, well': 'baik', 'half': 'setengah',
    'happy, joyful': 'senang', 'he, him': 'dia (laki-laki)', 'hot': 'panas',
    'hundred': 'seratus', 'love': 'cinta', 'man, male': 'laki-laki',
    'many, much': 'banyak', 'money': 'uang', 'moon, month': 'bulan',
    'mother': 'ibu', 'mouth': 'mulut', 'name': 'nama', 'new': 'baru',
    'nine': 'sembilan', 'noon': 'siang', 'not, no': 'tidak', 'now, present': 'sekarang',
    'one': 'satu', 'outside': 'luar', 'person, people': 'orang',
    'rain': 'hujan', 'school': 'sekolah', 'seven': 'tujuh', 'she, her': 'dia (perempuan)',
    'six': 'enam', 'small': 'kecil', 'snow': 'salju', 'tea': 'teh',
    'teacher, master': 'guru', 'ten': 'sepuluh', 'thank you': 'terima kasih',
    'this': 'ini', 'thousand': 'seribu', 'three': 'tiga', 'two': 'dua',
    'water': 'air', 'woman': 'perempuan', 'year': 'tahun', 'you': 'kamu, Anda',
    'younger brother': 'adik laki-laki', 'younger sister': 'adik perempuan', 'zero': 'nol',
    'to eat': 'makan', 'to drink': 'minum', 'to go': 'pergi', 'to come': 'datang',
    'to have': 'punya', 'to read': 'membaca', 'to write': 'menulis', 'to sleep': 'tidur',
    'to buy': 'membeli', 'to sell': 'menjual', 'to love': 'mencintai', 'to ask': 'bertanya',
    'to listen': 'mendengarkan', 'to sit': 'duduk', 'to sing': 'bernyanyi',
    'road, way': 'jalan', 'rice': 'beras', 'egg': 'telur', 'fire': 'api',
    'hand': 'tangan', 'electricity': 'listrik', 'east': 'timur', 'west': 'barat',
    'white': 'putih', 'star': 'bintang', 'song': 'lagu',
}

# Simplified Chinese — character meanings are mostly the same
ZH_HANS = {
    'Chinese, Han': '中国，汉', 'after, behind': '后面', 'again': '又，再',
    'air, energy': '空气，气', 'all, both': '都，全', 'also': '也',
    'big, large': '大', 'book': '书', 'car, vehicle': '车',
    'cat': '猫', 'chair': '椅子', 'child': '孩子', 'cold': '冷',
    'day, sun': '日，太阳', 'dog': '狗', 'eight': '八',
    'family, home': '家', 'father, dad': '爸爸', 'five': '五',
    'four': '四', 'friend': '朋友', 'good, well': '好', 'half': '半',
    'happy, joyful': '高兴', 'he, him': '他', 'hot': '热',
    'hundred': '百', 'love': '爱', 'man, male': '男',
    'many, much': '多', 'money': '钱', 'moon, month': '月',
    'mother': '妈妈', 'mouth': '口', 'name': '名字', 'new': '新',
    'nine': '九', 'noon': '中午', 'not, no': '不', 'now, present': '现在',
    'one': '一', 'outside': '外面', 'person, people': '人',
    'rain': '雨', 'school': '学校', 'seven': '七', 'she, her': '她',
    'six': '六', 'small': '小', 'snow': '雪', 'tea': '茶',
    'teacher, master': '老师', 'ten': '十', 'thank you': '谢谢',
    'this': '这', 'thousand': '千', 'three': '三', 'two': '二',
    'water': '水', 'woman': '女', 'year': '年', 'you': '你',
    'younger brother': '弟弟', 'younger sister': '妹妹', 'zero': '零',
    'to eat': '吃', 'to drink': '喝', 'to go': '去', 'to come': '来',
    'to have': '有', 'to read': '读', 'to write': '写', 'to sleep': '睡觉',
    'to buy': '买', 'to sell': '卖', 'to love': '爱', 'to ask': '问',
}

ZH_HANT = dict(ZH_HANS)

HI = {
    'big, large': 'बड़ा', 'book': 'किताब', 'cat': 'बिल्ली', 'child': 'बच्चा',
    'cold': 'ठंडा', 'dog': 'कुत्ता', 'eight': 'आठ', 'five': 'पाँच',
    'four': 'चार', 'friend': 'दोस्त', 'good, well': 'अच्छा', 'he, him': 'वह',
    'hot': 'गर्म', 'hundred': 'सौ', 'love': 'प्यार', 'money': 'पैसा',
    'mother': 'माँ', 'new': 'नया', 'nine': 'नौ', 'one': 'एक',
    'person, people': 'व्यक्ति', 'rain': 'बारिश', 'school': 'स्कूल',
    'seven': 'सात', 'she, her': 'वह (महिला)', 'six': 'छह', 'small': 'छोटा',
    'tea': 'चाय', 'teacher, master': 'शिक्षक', 'ten': 'दस', 'thank you': 'धन्यवाद',
    'this': 'यह', 'three': 'तीन', 'two': 'दो', 'water': 'पानी',
    'year': 'साल', 'you': 'तुम', 'zero': 'शून्य',
    'to eat': 'खाना', 'to drink': 'पीना', 'to go': 'जाना', 'to love': 'प्यार करना',
}

AR = {
    'big, large': 'كبير', 'book': 'كتاب', 'cat': 'قطة', 'child': 'طفل',
    'cold': 'بارد', 'dog': 'كلب', 'eight': 'ثمانية', 'five': 'خمسة',
    'four': 'أربعة', 'friend': 'صديق', 'good, well': 'جيد', 'he, him': 'هو',
    'hot': 'حار', 'hundred': 'مئة', 'love': 'حب', 'money': 'مال',
    'mother': 'أم', 'new': 'جديد', 'nine': 'تسعة', 'one': 'واحد',
    'person, people': 'شخص', 'rain': 'مطر', 'school': 'مدرسة',
    'seven': 'سبعة', 'she, her': 'هي', 'six': 'ستة', 'small': 'صغير',
    'tea': 'شاي', 'teacher, master': 'معلم', 'ten': 'عشرة', 'thank you': 'شكراً',
    'this': 'هذا', 'three': 'ثلاثة', 'two': 'اثنان', 'water': 'ماء',
    'year': 'سنة', 'you': 'أنت', 'zero': 'صفر',
    'to eat': 'يأكل', 'to drink': 'يشرب', 'to go': 'يذهب', 'to love': 'يحب',
}

PL = {
    'big, large': 'duży', 'book': 'książka', 'cat': 'kot', 'child': 'dziecko',
    'cold': 'zimno', 'dog': 'pies', 'friend': 'przyjaciel', 'good, well': 'dobrze',
    'he, him': 'on', 'love': 'miłość', 'mother': 'mama', 'new': 'nowy',
    'one': 'jeden', 'school': 'szkoła', 'she, her': 'ona', 'small': 'mały',
    'tea': 'herbata', 'teacher, master': 'nauczyciel', 'thank you': 'dziękuję',
    'this': 'to', 'three': 'trzy', 'two': 'dwa', 'water': 'woda',
    'year': 'rok', 'you': 'ty', 'zero': 'zero',
}

RO = {
    'big, large': 'mare', 'book': 'carte', 'cat': 'pisică', 'child': 'copil',
    'cold': 'frig', 'dog': 'câine', 'friend': 'prieten', 'good, well': 'bine',
    'he, him': 'el', 'love': 'dragoste', 'mother': 'mamă', 'new': 'nou',
    'one': 'unu', 'school': 'școală', 'she, her': 'ea', 'small': 'mic',
    'tea': 'ceai', 'teacher, master': 'profesor', 'thank you': 'mulțumesc',
    'this': 'acesta', 'three': 'trei', 'two': 'doi', 'water': 'apă',
    'year': 'an', 'you': 'tu', 'zero': 'zero',
}

UK = {
    'big, large': 'великий', 'book': 'книга', 'cat': 'кіт', 'child': 'дитина',
    'cold': 'холодно', 'dog': 'собака', 'friend': 'друг', 'good, well': 'добре',
    'he, him': 'він', 'love': 'любов', 'mother': 'мама', 'new': 'новий',
    'one': 'один', 'school': 'школа', 'she, her': 'вона', 'small': 'малий',
    'tea': 'чай', 'teacher, master': 'вчитель', 'thank you': 'дякую',
    'this': 'це', 'three': 'три', 'two': 'два', 'water': 'вода',
    'year': 'рік', 'you': 'ти', 'zero': 'нуль',
}

ALL_LOCALES = {
    'ja': JA, 'ko': KO, 'vi': VI, 'th': TH,
    'zh-Hans': ZH_HANS, 'zh-Hant': ZH_HANT,
    'id': ID, 'hi': HI, 'ar': AR,
    'pl': PL, 'ro': RO, 'uk': UK,
}

# ─── INSERT ──────────────────────────────────────────────────────────────
total = 0
for locale, trans_dict in ALL_LOCALES.items():
    rows = []
    for c in char_en:
        en_meaning = c['meaning']
        translated = trans_dict.get(en_meaning, en_meaning)
        rows.append({
            'character_id': c['character_id'],
            'locale': locale,
            'meaning': translated,
            'mnemonic': c.get('mnemonic', ''),
        })

    for i in range(0, len(rows), 100):
        batch = rows[i:i+100]
        status, n = supa_post('character_translations', batch)
        total += n
        print(f"  {locale}: batch {i//100+1} → {n} rows (status={status})")

print(f"\n{'='*60}")
print(f"Total character translations inserted: {total}")
print(f"{'='*60}")
